export enum GtActivities {
  'Game Drives',
  'Climbing / Trekking',
  'Great Migration',
  'Bird Watching',
  'Walking / Hiking',
  'Cultural Visits',
  'Beach Relaxation',
  'Snorkeling / Swimming',
  'Canoeing / Kayaking',
  'Balloon Safari',
  'Biking',
  'Night Game Drives',
  'Waterfalls',
  'Historical Visits',
  'Rock Climbing',
  'Caving / Caves',
  'Rock Art / Cave Painting',
  'Whale Watching',
  'Turtle Hatching',
  'Dolphin Watching',
  'Giant Tortoise Watching',
  'Chimpanzee Watching',
  'Scuba Diving',
  'Canopy Walkway',
  'Spice Farms',
  'Picnicking',
  'Dhow Cruise',
  'City Tours',
  'Fishing / Sport Fishing',
  'Camel / Horse Riding',
  'Museum / Monument',
  'Forest Walk',
  'Worship Site',
  'Wedding / Honeymoon',
  'Paragliding / Microflights',
}
