import type { Adventure } from "@/lib/adventures-data"
import type { DayTrip } from "@/lib/day-trips-data"
import type { Destination } from "@/lib/destinations-data"
import type { SafariPackage } from "@/lib/safaris-data"
import type { Trek } from "@/lib/treks-data"
import type { ZanzibarExperience } from "@/lib/zanzibar-experiences"

export const deSafariOverlays: Record<string, Partial<SafariPackage>> = {
  "big-five": {
    title: "3 Tage Big-Five-Safari",
    region: "Nordtansania",
    duration: "3 Tage",
    price: "Ab 1.200 $",
    description:
      "Die perfekte Kurzsafari für Erstbesucher, die die Big Five in Tarangire und am Lake Manyara erleben möchten.",
    highlights: ["Big-Five-Wildtiere", "Elefanten in Tarangire", "Landschaften am Lake Manyara", "Privater 4x4", "Sehr gutes Preis-Leistungs-Verhältnis"],
    itinerary: [
      { day: 1, title: "Arusha nach Tarangire", description: "Transfer in den Tarangire-Nationalpark mit Pirschfahrt am Nachmittag." },
      { day: 2, title: "Ganzer Tag in Tarangire", description: "Ausführliche Pirschfahrt mit Fokus auf Elefanten und Löwen." },
      { day: 3, title: "Lake Manyara und Rückfahrt", description: "Vormittag am Lake Manyara, anschließend Rückkehr nach Arusha." },
    ],
    includes: ["Parkgebühren", "Unterkunft", "Mahlzeiten", "Privater Guide", "4x4-Fahrzeug"],
  },
  "big-five-short": {
    title: "3 Tage Big-Five-Kurzreise",
    region: "Nordtansania",
    duration: "3 Tage",
    price: "Ab 1.200 $",
    description:
      "Intensive 3-Tage-Safari mit Schwerpunkt auf den Big Five in Tarangire und am Lake Manyara.",
    highlights: ["Kompakter Reiseverlauf", "Big-Five-Fokus", "Ideal für kurze Aufenthalte", "Privates Fahrzeug", "Erfahrener Guide"],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Transfer und Pirschfahrt im Tarangire-Nationalpark." },
      { day: 2, title: "Ganzer Tag in Tarangire", description: "Ausgedehnte Tierbeobachtung in Tarangire." },
      { day: 3, title: "Lake Manyara", description: "Pirschfahrt am Morgen, danach Rückkehr nach Arusha." },
    ],
    includes: ["Parkgebühren", "Unterkunft", "Mahlzeiten", "Guide", "Transport"],
  },
  "wonders-of-tanzania": {
    title: "6 Tage Wunder Tansanias",
    region: "Nordtansania",
    duration: "6 Tage",
    price: "Ab 2.800 $",
    description:
      "Umfassende Safari durch Tarangire, Serengeti und den Ngorongoro-Krater.",
    highlights: ["Serengeti-Ebenen", "Ngorongoro-Krater", "Elefanten in Tarangire", "Lodges der gehobenen Mittelklasse", "Ausgewogenes Reisetempo"],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Fahrt von Arusha in den Tarangire-Nationalpark." },
      { day: "2-3", title: "Serengeti", description: "Pirschfahrten im Serengeti-Nationalpark." },
      { day: "4-5", title: "Ngorongoro", description: "Kraterabstieg und Wildtierbeobachtung." },
      { day: 6, title: "Rückkehr", description: "Rückfahrt nach Arusha." },
    ],
    includes: ["Alle Parkgebühren", "Unterkunft", "Vollpension", "Privater Guide", "4x4 Land Cruiser"],
  },
  "bush-and-beach": {
    title: "8 Tage Luxus-Safari Bush und Strand",
    region: "Nordtansania und Sansibar",
    duration: "8 Tage",
    price: "Ab 5.400 $",
    description:
      "Kombinieren Sie eine Luxus-Safari in Serengeti und Ngorongoro mit entspannenden Tagen an den Stränden Sansibars.",
    highlights: ["Safari auf dem Northern Circuit", "Strandverlängerung auf Sansibar", "Besuch von Stone Town", "Luxus-Lodges", "Private Transfers"],
    itinerary: [
      { day: "1-5", title: "Northern Circuit", description: "Safari in Tarangire, Serengeti und Ngorongoro." },
      { day: 6, title: "Flug nach Sansibar", description: "Transfer zu Ihrem Strandresort auf Sansibar." },
      { day: 7, title: "Strand und Kultur", description: "Optionale Stone-Town-Besichtigung und Gewürztour." },
      { day: 8, title: "Abreise", description: "Strandmorgen und Transfer zum Flughafen." },
    ],
    includes: ["Safari-Logistik", "Inlandsflug nach Sansibar", "Strandhotel", "Ausgewählte Ausflüge", "Privater Guide"],
  },
  "great-migration-safari": {
    title: "Safari zur Großen Migration in der Serengeti",
    region: "Nordtansania",
    duration: "8 Tage",
    price: "Ab 4.600 $",
    description:
      "Erleben Sie eines der eindrucksvollsten Naturschauspiele der Welt: die Große Gnu-Migration.",
    highlights: ["Mara-Flussüberquerungen", "Big-Five-Sichtungen", "Privater 4x4", "Luxuriöse Zeltcamps"],
    itinerary: [
      { day: 1, title: "Ankunft in Arusha", description: "Transfer zu Ihrer Lodge für ein Briefing." },
      { day: "2-3", title: "Zentrale Serengeti", description: "Pirschfahrten im Herzen des Großkatzengebiets." },
      { day: "4-6", title: "Nördliche Serengeti", description: "Verfolgung der Migration nahe des Mara-Flusses." },
      { day: 7, title: "Ngorongoro-Krater", description: "Abstieg in das Paradies Afrikas." },
      { day: 8, title: "Abreise", description: "Rückkehr nach Arusha für Ihren Heimflug." },
    ],
    includes: ["Alle Parkgebühren", "Privater Guide", "Vollpension", "4x4 Land Cruiser"],
  },
  "private-tours": {
    title: "Private Safari-Touren nach Maß",
    region: "Ganz Tansania",
    duration: "Individuell",
    price: "Preis auf Anfrage",
    description:
      "Exklusiv gestaltete Reiseverläufe für Paare, Familien oder kleine Gruppen, die maximale Flexibilität suchen.",
    highlights: ["Persönlicher Privatguide", "Individueller Tagesablauf", "Sorgfältig ausgewählte Lodges", "Privater 4x4"],
    itinerary: [
      { day: "Hinweis", title: "Individuell planbare Tage", description: "Wir gestalten den Reiseverlauf rund um Ihre Interessen und Ihr bevorzugtes Tempo." },
    ],
    includes: ["Privater Transport", "Erfahrener Naturguide", "Persönliche Reiseplanung"],
  },
  "safari-vehicles": {
    title: "Unsere 4x4 Safari-Land-Cruiser",
    region: "Logistik",
    duration: "Technische Daten",
    price: "In Touren enthalten",
    description:
      "Unsere Flotte besteht aus speziell umgebauten 4x4-Land-Cruisern für das anspruchsvolle Gelände Tansanias.",
    highlights: ["Aufstelldach mit 360°-Sicht", "Ladeanschlüsse im Fahrzeug", "Kühlbox für kalte Getränke", "Funk mit großer Reichweite"],
    itinerary: [
      { day: "Komfort", title: "Platz und Sicht", description: "Verlängerte Rahmen für mehr Beinfreiheit und große Panoramafenster." },
      { day: "Sicherheit", title: "Wartung", description: "Jedes Fahrzeug wird nach jeder einzelnen Safari vollständig gewartet." },
    ],
    includes: ["Fensterplatz garantiert", "Schnorchel für Wasserdurchfahrten", "Nachschlagewerke und Ferngläser"],
  },
  "packing-list": {
    title: "Safari-Packliste - das Wichtigste",
    region: "Vorbereitung",
    duration: "Checkliste",
    price: "Expertenratgeber",
    description:
      "Stellen Sie sicher, dass Sie alles für ein komfortables und sicheres Abenteuer in der Wildnis dabeihaben.",
    highlights: ["Kleidung in neutralen Farben", "Sonnenschutz", "Gutes Fernglas", "Malariaprophylaxe"],
    itinerary: [
      { day: "Kleidung", title: "Was Sie tragen sollten", description: "Mehrere Schichten sind entscheidend. Morgens ist es kühl, nachmittags warm. Blau und Schwarz besser vermeiden." },
      { day: "Ausrüstung", title: "Wichtige Technik", description: "Kamera, Ersatzakkus und Powerbanks sind in abgelegenen Gebieten besonders wichtig." },
    ],
    includes: ["Standard-Checkliste", "Visa-Hinweise", "Gesundheitstipps"],
  },
  "honeymoon-safari": {
    title: "Romantische Flitterwochen-Safaris",
    region: "Romantisches Tansania",
    duration: "7-12 Tage",
    price: "Ab 5.200 $",
    description:
      "Verbinden Sie das Abenteuer der Wildnis mit intimem Luxus in den romantischsten Landschaften Afrikas.",
    highlights: ["Private Buschdinner", "Übernachtungen im Star-Bed", "Sansibar-Verlängerungen", "Heißluftballon-Safari"],
    itinerary: [
      { day: "Stil", title: "Intimer Luxus", description: "Wir wählen kleine, abgelegene Camps, die Privatsphäre und Romantik in den Mittelpunkt stellen." },
    ],
    includes: ["Paarmassage", "Champagner-Sundowner", "Private Transfers"],
  },
}

export const deDayTripOverlays: Record<string, Partial<DayTrip>> = {
  "chemka-hot-springs": {
    title: "Tagesausflug zu den Chemka Hot Springs",
    shortTitle: "Chemka Hot Springs",
    description:
      "Entfliehen Sie in das kristallklare Wasser der Chemka Hot Springs, einem Naturparadies am Fuß des Kilimandscharo. Genießen Sie ein erfrischendes Bad, entspannen Sie an sandigen Ufern und erleben Sie mineralreiches warmes Wasser in tropischer Umgebung.",
    highlight: "Baden in kristallklaren natürlichen Heißquellen",
    duration: "Ganztägig",
    location: "Kikuletwa, Kilimandscharo",
    highlights: ["Baden in natürlichen Heißquellen", "Entspannen an Sandufern", "Traditionelles Mittagessen am Wasser", "Panoramafahrt durch Kaffeeplantagen", "Großartige Fotomotive"],
    included: ["Eintrittsgebühren", "Professioneller Guide", "Privater Transport", "Mittagessen", "Trinkwasser"],
    notIncluded: ["Persönliche Ausgaben", "Trinkgelder", "Reiseversicherung"],
    itinerary: [
      { time: "07:00", activity: "Abholung von Ihrem Hotel in Arusha" },
      { time: "08:30", activity: "Panoramafahrt über Kaffeeplantagen nach Chemka" },
      { time: "09:30", activity: "Ankunft an den Chemka Hot Springs und Umziehen" },
      { time: "10:00", activity: "Schwimmen und Entspannen in den natürlichen Becken" },
      { time: "12:30", activity: "Mittagessen am Poolrand" },
      { time: "14:00", activity: "Freie Zeit zum Baden und Erkunden" },
      { time: "15:30", activity: "Rückfahrt nach Arusha" },
      { time: "17:00", activity: "Rückkehr zum Hotel" },
    ],
  },
  "lake-duluti": {
    title: "Tagesausflug zum Lake Duluti",
    shortTitle: "Lake Duluti",
    description:
      "Entdecken Sie die ruhige Schönheit des Lake Duluti, eines eindrucksvollen Kratersees unweit von Arusha. Unternehmen Sie einen geführten Waldspaziergang, beobachten Sie zahlreiche Vogelarten und genießen Sie eine Kanufahrt auf dem stillen Wasser.",
    highlight: "Kanufahrt auf einem malerischen Kratersee",
    duration: "Halbtägig / ganztägig",
    location: "Arusha",
    highlights: ["Geführter Waldspaziergang rund um den See", "Kanufahren auf dem Kratersee", "Vogelbeobachtung mit über 200 Arten", "Picknick am See", "Kulturelle Begegnungen mit lokalen Gemeinschaften"],
    included: ["Eintrittsgebühren", "Professioneller Guide", "Privater Transport", "Kanuverleih", "Mittagessen (Ganztagestour)", "Trinkwasser"],
    notIncluded: ["Persönliche Ausgaben", "Trinkgelder", "Reiseversicherung"],
    itinerary: [
      { time: "08:00", activity: "Abholung am Hotel in Arusha" },
      { time: "09:00", activity: "Ankunft am Lake Duluti und Treffen mit Ihrem Guide" },
      { time: "09:30", activity: "Geführter Spaziergang am Kraterrand" },
      { time: "11:00", activity: "Kanufahrt auf dem Lake Duluti" },
      { time: "12:30", activity: "Picknick am See" },
      { time: "14:00", activity: "Vogelbeobachtung und Fotografie" },
      { time: "15:30", activity: "Rückfahrt nach Arusha" },
      { time: "16:30", activity: "Rückkehr zum Hotel" },
    ],
  },
  "arusha-town-tour": {
    title: "Stadtrundgang durch Arusha",
    shortTitle: "Arusha Stadt",
    description:
      "Entdecken Sie Arusha mit einem lokalen Guide - Kulturstätten, lebendige Märkte und den Alltag der Safari-Hauptstadt Tansanias.",
    highlight: "Geführter Kulturspaziergang durch Arusha",
    duration: "Halbtägig",
    location: "Arusha",
    highlights: ["Wichtige Orte im Zentrum von Arusha", "Lokale Geschichte und Kultur", "Marktbesuche", "Kunsthandwerk und Souvenirstopps", "Flexibles privates Tempo"],
    included: ["Professioneller Guide", "Privater Transport", "Wasserflaschen"],
    notIncluded: ["Mahlzeiten", "Einkäufe", "Trinkgelder"],
    itinerary: [
      { time: "09:00", activity: "Hotelabholung in Arusha" },
      { time: "09:30", activity: "Stadtrundgang durch das Zentrum" },
      { time: "11:00", activity: "Besuch kultureller Orte und Märkte" },
      { time: "12:30", activity: "Optionale Restaurantempfehlung zum Mittagessen" },
      { time: "13:30", activity: "Rückkehr zum Hotel" },
    ],
  },
  "curios-gift-shops": {
    title: "Tour zu Souvenir- und Kunsthandwerksläden",
    shortTitle: "Souvenirs und Geschenke",
    description:
      "Besuchen Sie die besten Kunsthandwerksläden und Ateliers in Arusha für Massai-Perlenarbeiten, Tinga-Tinga-Malerei, Schnitzereien und handgefertigte Souvenirs.",
    highlight: "Authentisches tansanisches Kunsthandwerk und Geschenke",
    duration: "Halbtägig",
    location: "Arusha",
    highlights: ["Kunsthandwerks-Workshops", "Fair-Trade-Läden", "Massai-Perlenarbeiten", "Tinga-Tinga-Kunst", "Versandberatung verfügbar"],
    included: ["Guide", "Transport zwischen den Geschäften", "Wasserflaschen"],
    notIncluded: ["Einkäufe", "Versandkosten", "Trinkgelder"],
    itinerary: [
      { time: "09:00", activity: "Abholung und Einführung" },
      { time: "09:30", activity: "Besuch ausgewählter Läden und Studios" },
      { time: "12:00", activity: "Freie Zeit zum Einkaufen" },
      { time: "13:00", activity: "Rückkehr zum Hotel" },
    ],
  },
  "local-markets": {
    title: "Tour durch lokale Märkte",
    shortTitle: "Lokale Märkte",
    description:
      "Erleben Sie die farbenfrohen Märkte von Arusha - frische Produkte, Gewürze, Stoffe und den alltäglichen Rhythmus des tansanischen Lebens.",
    highlight: "Eindrucksvolles Markterlebnis",
    duration: "Halbtägig",
    location: "Arusha",
    highlights: ["Rundgang durch den Zentralmarkt", "Gewürze und frische Produkte", "Textilien und Handwerk", "Lokale Kostproben", "Ideal für Fotografie"],
    included: ["Lokaler Guide", "Marktführung", "Transport", "Wasser"],
    notIncluded: ["Essenskäufe", "Persönliche Einkäufe", "Trinkgelder"],
    itinerary: [
      { time: "08:30", activity: "Abholung am Morgen" },
      { time: "09:00", activity: "Geführter Rundgang durch die Markthallen" },
      { time: "11:00", activity: "Gewürz- und Gemüsebereich" },
      { time: "12:00", activity: "Rückkehr zum Hotel" },
    ],
  },
}

export const deZanzibarOverlays: Record<string, Partial<ZanzibarExperience>> = {
  "spice-tours": {
    title: "Gewürztouren auf Sansibar",
    description:
      "Spazieren Sie durch duftende Gewürzplantagen auf Sansibar und erfahren Sie, wie Nelken, Vanille, Zimt und Muskat die Geschichte und Küche der Insel geprägt haben.",
    highlight: "Praktisches Erlebnis auf einer Gewürzfarm",
    duration: "Halbtägig",
    price: "Ab 45 $ pro Person",
    highlights: ["Geführter Rundgang durch eine Gewürzplantage", "Verkostung frischer Tropenfrüchte", "Traditionelle Anwendungen von Gewürzen kennenlernen", "Lokales Mittagessen optional", "Perfekte Ergänzung nach der Safari"],
    included: ["Hotelabholung im Raum Stone Town", "Professioneller Guide", "Eintritt zur Gewürzfarm", "Fruchtverkostung"],
    itinerary: [
      { step: "Abholung am Morgen", detail: "Transfer von Ihrem Hotel oder aus Stone Town zu einer aktiven Gewürzfarm." },
      { step: "Plantagenführung", detail: "Geführter Rundgang mit Erklärung von Gewürzen, Kräutern und Tropenfrüchten." },
      { step: "Verkostung und Einkauf", detail: "Frische Produkte probieren und lokale Gewürzprodukte entdecken." },
      { step: "Rückkehr", detail: "Rückfahrt zum Hotel oder Weiterfahrt an den Strand." },
    ],
  },
  "cultural-tour": {
    title: "Kulturelle Tour durch Stone Town",
    description:
      "Erkunden Sie das UNESCO-Welterbe Stone Town mit einem lokalen Guide - geschnitzte Türen, historische Gassen, Märkte und lebendige Swahili-Kultur.",
    highlight: "Kulturerbe-Spaziergang durch Stone Town",
    duration: "Halbtägig",
    price: "Ab 40 $ pro Person",
    highlights: ["Historischer Rundgang durch Stone Town", "Bereich um das Old Fort und House of Wonders", "Lokale Märkte und Handwerkswerkstätten", "Swahili-Architektur und geschnitzte Türen", "Flexibles Tempo für Fotografen"],
    included: ["Professioneller lokaler Guide", "Geführter Rundgang", "Wasserflaschen"],
    itinerary: [
      { step: "Treffen mit dem Guide", detail: "Start an einem zentralen Treffpunkt in Stone Town oder an Ihrem Hotel." },
      { step: "Kulturspaziergang", detail: "Besuch wichtiger Sehenswürdigkeiten, Märkte und versteckter Innenhöfe." },
      { step: "Kulturelle Stopps", detail: "Einblicke in das arabische, persische, indische und afrikanische Erbe Sansibars." },
      { step: "Freie Zeit", detail: "Mittagsempfehlung und Rückkehr zum Hotel." },
    ],
  },
  "diving-snorkeling": {
    title: "Tauchen und Schnorcheln auf Sansibar",
    description:
      "Entdecken Sie das Mnemba-Atoll und die Korallenriffe Sansibars bei geführten Schnorchel- oder Tauchausflügen inklusive Ausrüstung und Bootstransfers.",
    highlight: "Kristallklare Riffe im Indischen Ozean",
    duration: "Ganztägig",
    price: "Ab 85 $ pro Person",
    highlights: ["Bootsausflug zu den Riffplätzen", "Schnorchelausrüstung inklusive", "Delfinbeobachtung saisonal möglich", "Leichtes Mittagessen auf Sandbänken", "PADI-Tauchoptionen auf Anfrage"],
    included: ["Bootstransfer", "Schnorchelausrüstung", "Guide", "Leichtes Mittagessen", "Getränke"],
    itinerary: [
      { step: "Hotelabholung", detail: "Morgendlicher Transfer zum Abfahrtsstrand." },
      { step: "Bootsausflug", detail: "Fahrt zum Mnemba-Atoll oder zu Riffen an der Nordküste." },
      { step: "Schnorchelstopps", detail: "Mehrere Stopps zum Erkunden der Riffe und Baden." },
      { step: "Rückkehr", detail: "Nachmittags Rückfahrt zu Ihrem Strandhotel." },
    ],
  },
  transfers: {
    title: "Flughafen- und Fährtransfers auf Sansibar",
    description:
      "Zuverlässige private Transfers zwischen dem internationalen Flughafen Abeid Amani Karume, Fährterminals, Stone Town und Strandresorts auf Sansibar.",
    highlight: "Tür-zu-Tür-Transfers auf der Insel",
    duration: "Auf Anfrage",
    price: "Ab 35 $ pro Fahrzeug",
    highlights: ["Persönlicher Empfang am Flughafen", "Transfers von Fährterminals", "Verbindungen zu Resorts und Stone Town", "Flugüberwachung inklusive", "24/7 Unterstützung von Gladiolus Tours"],
    included: ["Privatfahrzeug", "Englischsprachiger Fahrer", "Wasserflaschen", "Flug- und Fähren-Tracking"],
    itinerary: [
      { step: "Buchung", detail: "Teilen Sie uns bei der Bestätigung Ihre Flug- oder Fährdaten mit." },
      { step: "Empfang", detail: "Ihr Fahrer wartet mit einem Namensschild im Ankunftsbereich." },
      { step: "Direkttransfer", detail: "Komfortable Fahrt zu Ihrem Hotel oder zum Hafen." },
      { step: "Rückfahrt", detail: "Buchen Sie Ihren Rücktransfer gleich mit." },
    ],
  },
}

export const deAdventureOverlays: Record<string, Partial<Adventure>> = {
  "kilimanjaro-northern-circuit": {
    title: "9 Tage Kilimandscharo-Trek über den Northern Circuit",
    category: "Bergsteigen",
    description:
      "Der Northern Circuit ist die landschaftlich eindrucksvollste Route am Kilimandscharo mit großzügiger Akklimatisationszeit. Freuen Sie sich auf abgelegene alpine Grate, Gletscherblicke und ein ruhiges Gipfeltempo.",
    highlights: ["Längste Akklimatisationsphase für bessere Gipfelchancen", "Nordhänge mit weniger Bergsteigern", "Eigenes Summit-Support-Team", "Option auf privates Kratercamp"],
    itinerary: [
      { day: 1, title: "Ankunft und Ausrüstungscheck", description: "Ankunft in Arusha, Treffen mit Ihrem Hauptguide und ausführliches Briefing zu Ausrüstung und Gesundheit." },
      { day: 2, title: "Lemosho Gate nach Mti Mkubwa", description: "Trekking durch den Regenwald bis zum ersten Camp in ruhigem Akklimationstempo." },
      { day: 3, title: "Erkundung des Shira-Plateaus", description: "Überquerung offener Moorlandschaften mit weiten Blicken auf das Shira-Plateau." },
      { day: 4, title: "Akklimatisation an der Lava Tower", description: "Aufstieg zur Lava Tower für die Höhenanpassung, anschließend Abstieg zum tieferen Camp." },
      { day: 5, title: "Durchquerung des Northern Circuit", description: "Querung der Nordseite auf einer ruhigeren Route mit dramatischer alpiner Kulisse." },
      { day: 6, title: "Hochlager und Gipfelbriefing", description: "Frühe Ankunft im Hochlager, Flüssigkeitsaufnahme und Vorbereitung auf den Gipfelaufstieg." },
      { day: 7, title: "Gipfeltag", description: "Nachtaufstieg zum Uhuru Peak und anschließender Abstieg ins mittlere Camp." },
      { day: 8, title: "Abstieg nach Mweka", description: "Abstieg durch Moor- und Waldzonen mit Abschlussbriefing unterwegs." },
      { day: 9, title: "Abreise", description: "Transfer zurück nach Arusha oder Weiterreise zur Safari." },
    ],
    packages: [
      { name: "Classic Northern Circuit", duration: "9 Tage", price: "Ab 3.950 $", description: "Ausgewogene Trekkingreise mit Premium-Camps, vollem Guide-Team und privaten Transfers.", includes: ["Parkgebühren", "Vollpension", "Private Zelte", "Gipfelzertifikate"] },
      { name: "Northern Circuit + Safari", duration: "12 Tage", price: "Ab 5.900 $", description: "Ergänzen Sie drei Safaritage in Tarangire und Ngorongoro nach dem Gipfel.", includes: ["Safari-Lodges", "4x4-Fahrzeug", "Safari-Vollpension", "Parkgebühren"] },
    ],
  },
  "walking-safaris": {
    title: "Walking Safaris und Begegnungen mit indigenen Guides",
    category: "Walking Safaris",
    description:
      "Erkunden Sie die Wildnis zu Fuß mit spezialisierten Rangern und indigenen Guides. Folgen Sie Spuren, lernen Sie Bushcraft und genießen Sie intime Sundowner in der Natur.",
    highlights: ["Geführtes Tracking und Bushcraft", "Schonende Wanderrouten", "Sundowner am Flussufer", "Geschichtenrunden mit lokalen Gemeinschaften"],
    itinerary: [
      { day: 1, title: "Ankunft und Ranger-Briefing", description: "Treffen Sie Ihr Walking-Team und lernen Sie Sicherheitsregeln sowie Grundlagen des Trackings." },
      { day: 2, title: "Spurenlesen am Morgen", description: "Folgen Sie frischen Tierspuren und lernen Sie wichtige Arten und Lebensräume kennen." },
      { day: 3, title: "Eintauchen mit indigenen Guides", description: "Verbringen Sie Zeit mit lokalen Guides und entdecken Sie Ökologie und Traditionen." },
      { day: 4, title: "Flussspaziergang und Sundowner", description: "Erkunden Sie Wasserläufe und genießen Sie anschließend einen stilvollen Sundowner." },
      { day: 5, title: "Abreise oder Safari-Verlängerung", description: "Weitertransfer oder Verlängerung mit einer Fahrzeug-Safari in nahegelegene Parks." },
    ],
    packages: [
      { name: "Walking Safari Essentials", duration: "5 Tage", price: "Ab 2.150 $", description: "Geführte Wanderungen mit Boutique-Lodges und täglichen Ranger-Briefings.", includes: ["Wanderpermits", "Experten-Ranger", "Alle Mahlzeiten", "Transfers"] },
      { name: "Walking + Fly Camp", duration: "6 Tage", price: "Ab 2.950 $", description: "Mit einer Nacht unter freiem Himmel in einem Fly Camp.", includes: ["Fly-Camp-Aufbau", "Privatkoch", "Nachtwache", "Luxus-Lodges"] },
    ],
  },
  "zanzibar-coast": {
    title: "Sansibar-Küste und Gewürzkultur",
    category: "Strandurlaub",
    description:
      "Entspannen Sie an der Gewürzküste mit kuratierten Stone-Town-Touren, Dhow-Fahrten und Boutique-Strandaufenthalten, die Kultur und Erholung verbinden.",
    highlights: ["Stone-Town-Spaziergänge", "Private Gewürzfarm-Tour", "Dhow-Segeln bei Sonnenuntergang", "Spa- und Wellness-Angebote"],
    itinerary: [
      { day: 1, title: "Ankunft in Stone Town", description: "Check-in im Heritage-Hotel und abendliche Food-Tour mit Guide." },
      { day: 2, title: "Gewürzfarm und Kultur", description: "Besuch einer Gewürzplantage und kultureller Sehenswürdigkeiten mit Historiker-Guide." },
      { day: 3, title: "Transfer an den Strand", description: "Umzug an die Küste für Strandzeit, Schnorcheln und Spa." },
      { day: 4, title: "Erlebnisse auf dem Ozean", description: "Private Dhow-Fahrt, Riffschnorcheln und Meeresfrüchte-Dinner." },
      { day: 5, title: "Abreise", description: "Freier Morgen und Transfer zum Flughafen." },
    ],
    packages: [
      { name: "Spice Coast Escape", duration: "5 Tage", price: "Ab 1.900 $", description: "Heritage-Hotel plus Strandresort mit ausgewählten Erlebnissen.", includes: ["Stone-Town-Guide", "Strandresort", "Flughafentransfers", "Frühstück"] },
      { name: "Romance on the Coast", duration: "6 Tage", price: "Ab 2.450 $", description: "Mit privaten Dinnern, Spa-Ritualen und Segeln bei Sonnenuntergang.", includes: ["Privates Dinner mit Chef", "Spa-Rituale", "Dhow-Fahrt", "Butler-Service"] },
    ],
  },
  "northern-circuit-adventure": {
    title: "Abenteuer-Safaris auf dem Northern Circuit",
    category: "Abenteuer-Safaris",
    description:
      "Verbinden Sie Pirschfahrten mit aktiven Erlebnissen wie Kanufahren, Radfahren, Kraterrand-Wanderungen und Fototagen - abgestimmt auf die beste Wildtiersaison.",
    highlights: ["Kanusafaris am Lake Manyara", "Wanderungen am Kraterrand", "Fotografie-Coaching", "Privater 4x4 mit flexiblem Routing"],
    itinerary: [
      { day: 1, title: "Ankunft und Orientierung in Arusha", description: "Willkommensbriefing mit Ihrem Safarileiter und Vorbereitung der Ausrüstung." },
      { day: 2, title: "Tarangire-Pirschfahrten", description: "Fahrten am Morgen und Abend mit optionalem Radausflug." },
      { day: 3, title: "Kanutour am Lake Manyara", description: "Kanusafari mit anschließendem kulturellem Dorferlebnis." },
      { day: 4, title: "Ngorongoro-Kraterrand-Wanderung", description: "Geführte Wanderung am Kraterrand mit Picknick." },
      { day: 5, title: "Fotografie in der Serengeti", description: "Golden-Hour-Fotografie mit erfahrenen Guides." },
      { day: 6, title: "Abreise oder Verlängerung", description: "Verlängerung nach Sansibar oder Abreise über den Kilimanjaro Airport." },
    ],
    packages: [
      { name: "Northern Adventure Core", duration: "6 Tage", price: "Ab 3.200 $", description: "Aktive Safari mit privatem Guide und flexiblem Tagesablauf.", includes: ["Privater Guide", "Luxus-Camps", "Alle Mahlzeiten", "Parkgebühren"] },
      { name: "Northern Adventure + Zanzibar", duration: "9 Tage", price: "Ab 4.850 $", description: "Drei Strandtage auf Sansibar mit ausgewählten kulturellen Stopps.", includes: ["Strandresort", "Inseltransfers", "Dhow-Fahrt", "Dinner mit Chef"] },
    ],
  },
}

export const deDestinationOverlays: Record<string, Partial<Destination>> = {
  "serengeti-national-park": {
    title: "Serengeti-Nationalpark",
    location: "Tansania",
    duration: "5 Tage",
    price: "Ab 2.500 $",
    description: "Erleben Sie das weltberühmte Serengeti-Ökosystem, Heimat der Großen Migration und zahlreicher Wildtiere wie Löwen, Leoparden, Elefanten und Geparden.",
    highlights: ["Große Gnu-Migration erleben", "Big-Five-Pirschfahrten", "Heißluftballon-Safari bei Sonnenaufgang", "Besuch traditioneller Massai-Dörfer", "Perfekt für Tierfotografie"],
    itinerary: [
      { day: 1, title: "Ankunft und Transfer in die Serengeti", description: "Treffen am Kilimanjaro Airport und Transfer in den Serengeti-Nationalpark mit Pirschfahrt am Abend." },
      { day: 2, title: "Ganzer Tag Pirschfahrt", description: "Pirschfahrten am Morgen und Nachmittag in der zentralen Serengeti mit Busch-Picknick." },
      { day: 3, title: "Heißluftballon-Safari", description: "Optionale Ballonfahrt bei Sonnenaufgang mit Champagnerfrühstück, danach Pirschfahrt." },
      { day: 4, title: "Massai-Kulturerlebnis", description: "Besuch eines traditionellen Massai-Dorfes und abendliche Pirschfahrt." },
      { day: 5, title: "Letzte Pirschfahrt und Abreise", description: "Morgendliche Pirschfahrt und Rücktransfer nach Arusha." },
    ],
    included: ["Flughafentransfers", "Unterkunft in Luxus-Zeltcamps", "Alle Mahlzeiten während der Safari", "Professioneller Guide und 4x4-Fahrzeug", "Parkgebühren", "Wasserflaschen"],
    excluded: ["Internationale Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Heißluftballon-Fahrt (550 $)", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-8 Personen",
  },
  "ngorongoro-crater": {
    title: "Ngorongoro-Krater",
    location: "Tansania",
    duration: "4 Tage",
    price: "Ab 2.000 $",
    description: "Erkunden Sie die größte intakte Vulkankaldera der Welt - ein natürliches Schutzgebiet mit einer der höchsten Wildtierdichten Afrikas.",
    highlights: ["Pirschfahrten auf dem Kraterboden", "Sichtungen von Spitzmaulnashörnern", "Archäologische Stätte Olduvai Gorge", "Eindrucksvolle Vulkanlandschaften", "Flamingos am Lake Magadi"],
    itinerary: [
      { day: 1, title: "Ankunft und Kraterrand", description: "Transfer von Arusha nach Ngorongoro. Abend in der Lodge mit Aussicht auf den Krater." },
      { day: 2, title: "Safari im Krater", description: "600 Meter Abstieg auf den Kraterboden für einen ganzen Tag Tierbeobachtung." },
      { day: 3, title: "Olduvai Gorge und Kultur", description: "Besuch der archäologischen Fundstätte und kulturelles Massai-Erlebnis." },
      { day: 4, title: "Abreise", description: "Freier Morgen und Rückfahrt nach Arusha." },
    ],
    included: ["Alle Transfers", "Lodge-Unterkunft", "Alle Mahlzeiten", "Kratergebühren und Permits", "Professioneller Guide", "Kraterabstieg"],
    excluded: ["Internationale Flüge", "Alkoholische Getränke", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Ganzjährig",
    groupSize: "2-6 Personen",
  },
  "tarangire-national-park": {
    title: "Tarangire-Nationalpark",
    location: "Tansania",
    duration: "3 Tage",
    price: "Ab 1.500 $",
    description: "Tarangire ist berühmt für große Elefantenherden und uralte Baobabs und bietet intensive Wildtiererlebnisse in eindrucksvoller Landschaft.",
    highlights: ["Große Elefantenpopulationen", "Uralte Baobabbäume", "Baumkletternde Löwen", "Über 550 Vogelarten", "Walking Safaris verfügbar"],
    itinerary: [
      { day: 1, title: "Arusha nach Tarangire", description: "Morgendliche Fahrt nach Tarangire, am Nachmittag Pirschfahrt mit Fokus auf Elefanten." },
      { day: 2, title: "Ganztägige Safari", description: "Ganzer Tag im Park mit Picknick und optionaler Walking Safari." },
      { day: 3, title: "Morgenfahrt und Rückkehr", description: "Frühe Pirschfahrt und anschließend Rückfahrt nach Arusha." },
    ],
    included: ["Transport im 4x4", "Lodge-Unterkunft", "Alle Mahlzeiten", "Parkgebühren", "Professioneller Guide"],
    excluded: ["Internationale Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-6 Personen",
  },
  "lake-manyara-national-park": {
    title: "Lake-Manyara-Nationalpark",
    location: "Tansania",
    duration: "2 Tage",
    price: "Ab 900 $",
    description: "Kompakter Park mit vielfältigen Lebensräumen vom Grundwasserwald bis zum alkalischen See, bekannt für baumkletternde Löwen.",
    highlights: ["Baumkletternde Löwen", "Flamingoschwärme am See", "Waldelefanten", "Canopy-Walkway", "Heiße Quellen"],
    itinerary: [
      { day: 1, title: "Ankunft und Pirschfahrt", description: "Transfer zum Lake Manyara und Pirschfahrt durch Wald und Uferzone." },
      { day: 2, title: "Canopy Walk und Abreise", description: "Morgendlicher Canopy Walk, letzte Pirschfahrt und Rückkehr nach Arusha." },
    ],
    included: ["Alle Transfers", "Lodge-Unterkunft", "Mahlzeiten", "Parkeintritt", "Guide-Service"],
    excluded: ["Flüge", "Versicherung", "Persönliche Gegenstände", "Trinkgelder"],
    bestTime: "Ganzjährig",
    groupSize: "2-6 Personen",
  },
  "mount-kilimanjaro-trek": {
    title: "Trek am Mount Kilimanjaro",
    location: "Tansania",
    duration: "8 Tage",
    price: "Ab 4.500 $",
    description: "Besteigen Sie Afrikas höchsten Berg über die landschaftlich reizvolle Lemosho-Route mit hervorragender Akklimatisation und hohen Erfolgsraten.",
    highlights: ["Uhuru Peak auf 5.895 m erreichen", "Mehrere Klimazonen durchqueren", "Spektakuläre Bergpanoramen", "Professionelle Bergführer", "Hohe Gipfelerfolgsquote"],
    itinerary: [
      { day: 1, title: "Londorossi Gate nach Mti Mkubwa", description: "Registrierung und Trekking durch den Regenwald bis zum ersten Camp." },
      { day: 2, title: "Mti Mkubwa nach Shira 1", description: "Aufstieg auf das Shira-Plateau durch Moorlandschaft." },
      { day: 3, title: "Shira 1 nach Shira 2", description: "Akklimatisationstag über das Shira-Plateau." },
      { day: 4, title: "Shira 2 nach Barranco", description: "Aufstieg zur Lava Tower und anschließender Abstieg zur Höhenanpassung." },
      { day: 5, title: "Barranco nach Karanga", description: "Über die Barranco Wall nach Karanga Camp." },
      { day: 6, title: "Karanga nach Barafu", description: "Kurzer Aufstieg ins Hochlager und Vorbereitung auf den Gipfel." },
      { day: 7, title: "Gipfeltag", description: "Nachtaufstieg zum Uhuru Peak und Abstieg zum Mweka Camp." },
      { day: 8, title: "Mweka zur Gate", description: "Letzter Abstieg durch den Regenwald und Übergabe der Zertifikate." },
    ],
    included: ["Berggenehmigungen", "Campingausrüstung", "Alle Mahlzeiten am Berg", "Professionelle Guides und Träger", "Rettungsgebühren"],
    excluded: ["Internationale Flüge", "Visum", "Reiseversicherung", "Persönliche Ausrüstung", "Trinkgelder für die Crew"],
    bestTime: "Januar-März, Juni-Oktober",
    groupSize: "2-12 Personen",
  },
  "ruaha-national-park": {
    title: "Ruaha-Nationalpark",
    location: "Tansania",
    duration: "4 Tage",
    price: "Ab 2.200 $",
    description: "Entdecken Sie Tansanias wilden Süden: dramatische Flusslandschaften, wenig Verkehr und hervorragende Raubtiersichtungen im abgelegenen Ruaha.",
    highlights: ["Abgelegene Pirschfahrten ohne Massen", "Starke Chancen auf Löwen und Leoparden", "Großartige Vogelbeobachtung am Great Ruaha River", "Geführte Wanderungen in ausgewählten Bereichen", "Stimmungsvolle Sundowner im Busch"],
    itinerary: [
      { day: 1, title: "Anreise per Flug und Abendfahrt", description: "Ankunft an der Landepiste, Check-in im Camp und Pirschfahrt zur goldenen Stunde." },
      { day: 2, title: "Ganzer Tag in Ruaha", description: "Pirschfahrten am Morgen und Nachmittag entlang von Flussbetten und Savannen." },
      { day: 3, title: "Walking-Safari-Option", description: "Optionale geführte Wanderung zu Spuren und Ökologie, danach entspannte Pirschfahrt." },
      { day: 4, title: "Letzte Fahrt und Abreise", description: "Frühe Pirschfahrt und Transfer zur Landepiste." },
    ],
    included: ["Parkgebühren", "Unterkunft", "Mahlzeiten", "Professioneller Guide", "Pirschfahrten", "Transfers in Ruaha"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-6 Personen",
  },
  "nyerere-national-park": {
    title: "Nyerere-Nationalpark",
    location: "Tansania",
    duration: "3 Tage",
    price: "Ab 1.850 $",
    description: "Erkunden Sie das Rufiji-Ökosystem mit einer Mischung aus klassischen Pirschfahrten und wasserbasierten Abenteuern in einem der größten Schutzgebiete Afrikas.",
    highlights: ["Bootssafaris auf dem Rufiji", "Hervorragende Sichtungen von Elefanten und Flusspferden", "Walking-Safari-Optionen", "Entspanntes Tempo mit wenigen Fahrzeugen", "Schöne Sonnenuntergänge am Fluss"],
    itinerary: [
      { day: 1, title: "Ankunft und Flussfahrt", description: "Ankunft und Check-in im Camp, danach Bootssafari am späten Nachmittag." },
      { day: 2, title: "Pirschfahrten", description: "Morgendliche Fahrt über Flutebenen und Pirschfahrt am Nachmittag zu Wasserstellen." },
      { day: 3, title: "Morgenaktivität und Abreise", description: "Optionale kurze Wanderung oder letzte Fahrt, anschließend Weitertransfer." },
    ],
    included: ["Unterkunft", "Mahlzeiten", "Parkgebühren", "Bootssafari", "Pirschfahrten", "Guide-Service"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Einkäufe", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-8 Personen",
  },
  "zanzibar-island-escape": {
    title: "Sansibar Insel-Auszeit",
    location: "Tansania",
    duration: "4 Tage",
    price: "Ab 1.300 $",
    description: "Beenden Sie Ihre Safari mit Meeresbrisen, Dhow-Fahrten und entspannten Morgenstunden an Sansibars weißen Sandstränden.",
    highlights: ["Entspannung am Strand", "Erkundung von Stone Town", "Schnorcheln und Riffausflüge", "Dhow-Sonnenuntergangsfahrt", "Swahili-Küche und Gewürztouren"],
    itinerary: [
      { day: 1, title: "Ankunft und Strandzeit", description: "Transfer zum Hotel und Ankommen im Inselrhythmus mit Sonnenuntergangsschwimmen." },
      { day: 2, title: "Stone Town und Kultur", description: "Erkunden Sie Gassen und Märkte von Stone Town und genießen Sie einen entspannten Abend am Meer." },
      { day: 3, title: "Ausflug auf dem Ozean", description: "Wählen Sie Schnorcheln, Sandbank-Picknick oder eine Riffkreuzfahrt je nach Bedingungen." },
      { day: 4, title: "Abreise", description: "Letzter Strandmorgen und Transfer zum Flughafen." },
    ],
    included: ["Transfers", "Unterkunft", "Frühstück", "Ausgewählte Ausflüge"],
    excluded: ["Flüge", "Mittag- und Abendessen", "Reiseversicherung", "Persönliche Ausgaben"],
    bestTime: "Juni bis März",
    groupSize: "2-8 Personen",
  },
  "saadani-national-park": {
    title: "Saadani-Nationalpark",
    location: "Tansania",
    duration: "3 Tage",
    price: "Ab 1.600 $",
    description: "Wo Busch auf Strand trifft: Saadani verbindet Küstenlandschaften mit Tierbeobachtung und eignet sich hervorragend als besondere Tansania-Verlängerung.",
    highlights: ["Safari-Landschaften an der Küste", "Pirschfahrten mit Meereskulisse", "Bootsfahrten und Flusstierwelt", "Ruhige Atmosphäre mit wenig Andrang", "Perfekt für kurze Verlängerungen"],
    itinerary: [
      { day: 1, title: "Ankunft und Pirschfahrt am Nachmittag", description: "Anreise und Pirschfahrt durch Küstenebenen und Flusskorridore." },
      { day: 2, title: "Pirschfahrt und Flussoption", description: "Morgendliche Pirschfahrt und optionaler Flussausflug je nach Saison." },
      { day: 3, title: "Letzter Morgen und Abreise", description: "Kurze Morgenaktivität und anschließender Transfer." },
    ],
    included: ["Unterkunft", "Mahlzeiten", "Parkgebühren", "Pirschfahrten", "Guide-Service"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-8 Personen",
  },
  "mahale-mountains-national-park": {
    title: "Mahale-Mountains-Nationalpark",
    location: "Tansania",
    duration: "5 Tage",
    price: "Ab 3.400 $",
    description: "Reisen Sie an den Tanganjikasee für ein Schimpansen-Trekking in Mahale - eines der lohnendsten und abgeschiedensten Primatenerlebnisse Tansanias.",
    highlights: ["Schimpansen-Trekking", "Landschaften am Tanganjikasee", "Wanderungen in bewaldeten Bergen", "Fly-in-Abenteuer in abgelegener Region", "Ideal für Naturfreunde"],
    itinerary: [
      { day: 1, title: "Ankunft und Seeufer", description: "Ankunft per Flug oder Boot, Einchecken und Zeit am Ufer." },
      { day: 2, title: "Schimpansen-Trekking", description: "Morgendliche Wanderung mit erfahrenen Trackern auf der Suche nach Schimpansen." },
      { day: 3, title: "Zweites Trekking oder Wanderung", description: "Wahl zwischen erneutem Trekking oder längerer Waldwanderung." },
      { day: 4, title: "Zeit am See", description: "Entspannung beim Schwimmen, Kajakfahren oder einer ruhigen Bootsfahrt." },
      { day: 5, title: "Abreise", description: "Transfer zur Weiterreise." },
    ],
    included: ["Parkgebühren", "Unterkunft", "Mahlzeiten", "Schimpansen-Trekking", "Lokale Transfers"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-6 Personen",
  },
  "lake-natron": {
    title: "Lake Natron",
    location: "Tansania",
    duration: "2 Tage",
    price: "Ab 750 $",
    description: "Besuchen Sie eine der eindrucksvollsten Landschaften Ostafrikas - alkalische Gewässer voller Flamingos, vulkanische Kulissen und das Tor zum Ol Doinyo Lengai.",
    highlights: ["Kolonien von Zwergflamingos", "Vulkanische Landschaften", "Wasserfälle und Massai-Kultur", "Northern Circuit abseits der üblichen Routen", "Tolle Fotomotive"],
    itinerary: [
      { day: 1, title: "Arusha nach Lake Natron", description: "Panoramafahrt durch Massai-Dörfer mit Stopps an Wasserfällen und Aussichtspunkten." },
      { day: 2, title: "Seeufer und Rückfahrt", description: "Morgen am Seeufer mit Flamingos und Landschaftspanoramen, danach Rückkehr nach Arusha." },
    ],
    included: ["Transport", "Unterkunft", "Mahlzeiten", "Guide-Service", "Naturschutzgebühren"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Juni bis Oktober",
    groupSize: "2-6 Personen",
  },
  "arusha-national-park": {
    title: "Arusha-Nationalpark",
    location: "Tansania",
    duration: "1 Tag",
    price: "Ab 350 $",
    description: "Ein kompaktes Juwel am Fuß des Mount Meru - Giraffen, Büffel, Colobus-Affen und Kraterseen nur wenige Minuten von Arusha entfernt.",
    highlights: ["Kulisse des Mount Meru", "Aussichtspunkte am Ngurdoto-Krater", "Vogelwelt an den Momella-Seen", "Walking Safaris möglich", "Ideal zur Akklimatisation vor dem Kilimandscharo"],
    itinerary: [
      { day: 1, title: "Ganztägige Pirschfahrt", description: "Abholung am Morgen, Safari durch Wald und Seen, Picknick und Rückfahrt nach Arusha." },
    ],
    included: ["Parkgebühren", "Privater 4x4", "Professioneller Guide", "Picknick-Mittagessen", "Hoteltransfers"],
    excluded: ["Flüge", "Reiseversicherung", "Persönliche Ausgaben", "Trinkgelder"],
    bestTime: "Ganzjährig",
    groupSize: "2-6 Personen",
  },
}

export const deTrekOverlays: Record<string, Partial<Trek>> = {
  "kilimanjaro-marangu-route": {
    title: "Marangu-Route",
    headline: "5 Tage Marangu-Route - Kilimandscharo-Besteigung",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "5 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Die einzige Kilimandscharo-Route mit Hüttenunterkunft. Ideal für Einsteiger, die Komfort und einen kürzeren Gipfelverlauf suchen.",
    overview: "Die Marangu-Route ist die etablierteste und komfortabelste Möglichkeit, den Kilimandscharo zu besteigen. Sie ist die einzige Route mit Schlafhütten und eignet sich gut für Trekker, die nicht zelten möchten.",
    priceFrom: "2.100 $ pro Person",
    highlights: ["Einzige Route mit Hüttenunterkunft", "Ideal für Einsteiger", "Gut angelegter und gleichmäßiger Pfad", "Klassischer Gipfelaufstieg über Gilman's Point", "Komfortable Hütten in jedem Camp"],
    whyChoose: ["Hütten statt Camping", "Kürzere Dauer und einfache Logistik", "Geeignet für mittlere Fitness", "Gute Gipfelchancen bei richtigem Tempo"],
    itinerary: [
      { day: "Tag 1", title: "Marangu Gate nach Mandara Hut", description: "Beginn des Aufstiegs durch üppigen Regenwald bis zur Mandara Hut (2.700 m)." },
      { day: "Tag 2", title: "Mandara Hut nach Horombo Hut", description: "Aufstieg ins Moorland mit Blick auf Mawenzi und Kibo bis zur Horombo Hut." },
      { day: "Tag 3", title: "Horombo Hut nach Kibo Hut", description: "Überquerung des alpinen Sattels zwischen Mawenzi und Kibo bis Kibo Hut." },
      { day: "Tag 4", title: "Gipfeltag und Abstieg nach Horombo", description: "Nachtaufstieg zum Uhuru Peak und anschließender Abstieg zur Horombo Hut." },
      { day: "Tag 5", title: "Horombo Hut nach Marangu Gate", description: "Letzter Abstieg durch den Regenwald und Übergabe des Zertifikats." },
    ],
  },
  "kilimanjaro-machame-route": {
    title: "Machame-Route",
    headline: "7 Tage Machame-Route - Kilimandscharo-Besteigung",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "7 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Die beliebteste Trekkingroute am Kilimandscharo mit spektakulären Landschaften und sehr gutem Akklimatisationsprofil.",
    overview: "Die Machame-Route, auch Whisky-Route genannt, ist der populärste Weg auf den Kilimandscharo. Dank ihres Profils 'hoch steigen, tief schlafen' bietet sie sehr gute Erfolgschancen am Gipfel.",
    priceFrom: "2.200 $ pro Person",
    highlights: ["Beliebteste Kilimandscharo-Route", "Sehr gutes Akklimatisationsprofil", "Abwechslungsreiche Landschaften", "Ikonische Barranco Wall", "Hohe Gipfelerfolgsquote"],
    whyChoose: ["Ausgewogenes Verhältnis von Herausforderung und Erlebnis", "Ideal für abenteuerlustige Trekker", "Sehr abwechslungsreiche Route", "Gute Erfolgsstatistik"],
    itinerary: [
      { day: "Tag 1", title: "Machame Gate nach Machame Camp", description: "Trekking durch dichten Regenwald bis zum Machame Camp (3.000 m)." },
      { day: "Tag 2", title: "Machame Camp nach Shira 2", description: "Steiler Aufstieg ins Moorland bis zum Shira-Plateau." },
      { day: "Tag 3", title: "Shira 2 - Lava Tower - Barranco", description: "Akklimatisationstag über die Lava Tower und Abstieg nach Barranco." },
      { day: "Tag 4", title: "Barranco nach Karanga", description: "Aufstieg über die Barranco Wall und weiter nach Karanga Camp." },
      { day: "Tag 5", title: "Karanga nach Barafu", description: "Erreichen des Barafu Camps und Vorbereitung auf die Gipfelnacht." },
      { day: "Tag 6", title: "Gipfel und Mweka Camp", description: "Nachtaufstieg zum Uhuru Peak und Abstieg zum Mweka Camp." },
      { day: "Tag 7", title: "Mweka Camp nach Mweka Gate", description: "Letzter Abstieg durch den Regenwald und Rückkehr nach Arusha oder Moshi." },
    ],
  },
  "kilimanjaro-lemosho-route": {
    title: "Lemosho-Route",
    headline: "8 Tage Lemosho-Route - Landschaftlich eindrucksvolle Kilimandscharo-Besteigung",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "8 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Eine der schönsten Kilimandscharo-Routen mit wenig Andrang, wildem Start und sehr hoher Gipfelerfolgsquote.",
    overview: "Die Lemosho-Route gilt als eine der schönsten Möglichkeiten, den Kilimandscharo zu besteigen. Sie startet an der Westseite, führt über das weite Shira-Plateau und bietet eine hervorragende Akklimatisation.",
    priceFrom: "2.380 $ pro Person",
    highlights: ["Landschaftlich besonders reizvolle Route", "Wenig Andrang", "Ausgezeichneter Akklimatisationsplan", "Sehr hohe Erfolgsquote", "Abgelegener westlicher Anstieg"],
    whyChoose: ["Premium-Trekkingerlebnis", "Ideal für ambitionierte Trekker", "Weniger überlaufen als Machame", "Längere Akklimatisation für mehr Sicherheit"],
    itinerary: [
      { day: "Tag 1", title: "Londorossi Gate nach Mti Mkubwa", description: "Start im ursprünglichen Regenwald auf der abgelegenen Westseite." },
      { day: "Tag 2", title: "Mti Mkubwa nach Shira 1", description: "Verlassen des Waldes und Aufstieg ins Moorland bis Shira 1." },
      { day: "Tag 3", title: "Shira 1 nach Shira 2", description: "Leichte Wanderung über das Shira-Plateau mit weiten Ausblicken." },
      { day: "Tag 4", title: "Shira 2 - Lava Tower - Barranco", description: "Aufstieg zur Lava Tower und Abstieg nach Barranco zur Akklimatisation." },
      { day: "Tag 5", title: "Barranco nach Karanga", description: "Über die Barranco Wall und weiter zum Karanga Camp." },
      { day: "Tag 6", title: "Karanga nach Barafu", description: "Ankunft im Hochlager Barafu und Vorbereitung auf die Gipfelnacht." },
      { day: "Tag 7", title: "Gipfel und Mweka Camp", description: "Nachtaufstieg über Stella Point zum Uhuru Peak, anschließend Abstieg." },
      { day: "Tag 8", title: "Mweka Camp nach Mweka Gate", description: "Letzter Abstieg durch den Regenwald und Feier des Erfolgs." },
    ],
  },
  "kilimanjaro-rongai-route": {
    title: "Rongai-Route",
    headline: "6 Tage Rongai-Route - Nördlicher Kilimandscharo-Anstieg",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "6 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Die einzige Kilimandscharo-Route von Norden nahe der kenianischen Grenze. Ruhig, trocken und besonders reizvoll.",
    overview: "Die Rongai-Route nähert sich dem Kilimandscharo von der Nordseite und ist meist trockener und ruhiger als südliche Wege. Sie eignet sich hervorragend in feuchteren Jahreszeiten.",
    priceFrom: "2.150 $ pro Person",
    highlights: ["Am wenigsten frequentierte Kilimandscharo-Route", "Trockene Bedingungen fast ganzjährig", "Sanfter Anstieg", "Besondere nordseitige Ausblicke", "Wildtierbeobachtungen an den unteren Hängen"],
    whyChoose: ["Ideal in Regenzeiten", "Weniger Verkehr als auf den Süd-Routen", "Konstantes Steigungsprofil", "Ruhigere und wildere Atmosphäre"],
    itinerary: [
      { day: "Tag 1", title: "Rongai Gate nach Simba Camp", description: "Beginn auf den bewaldeten Nordhängen bis zum Simba Camp." },
      { day: "Tag 2", title: "Simba Camp nach Kikelewa Camp", description: "Aufstieg ins Moorland mit Blick auf Mawenzi und die nördlichen Ebenen." },
      { day: "Tag 3", title: "Kikelewa nach Mawenzi Tarn", description: "Aufstieg in ein eindrucksvolles alpines Tal bis Mawenzi Tarn." },
      { day: "Tag 4", title: "Mawenzi Tarn nach Kibo Hut", description: "Überquerung des alpinen Sattels bis zur Kibo Hut." },
      { day: "Tag 5", title: "Gipfel und Horombo Hut", description: "Nachtaufstieg zum Uhuru Peak über Gilman's Point und Abstieg nach Horombo." },
      { day: "Tag 6", title: "Horombo Hut nach Marangu Gate", description: "Abstieg durch den Regenwald und Rückfahrt." },
    ],
  },
  "umbwe-route": {
    title: "Umbwe-Route",
    headline: "6 Tage Umbwe-Route - Steiler Kilimandscharo-Anstieg",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "6 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Die steilste und direkteste Route am Kilimandscharo - ideal für erfahrene Trekker mit Lust auf echte Herausforderung.",
    overview: "Die Umbwe-Route ist der steilste Weg zum Kilimandscharo-Gipfel. Sie steigt rasch durch Wald und über Grate an und ist daher besonders anspruchsvoll.",
    priceFrom: "2.150 $ pro Person",
    highlights: ["Steiler und direkter Anstieg", "Weniger frequentiert", "Schneller Zugang zum Barranco-Tal", "Anspruchsvolle Gratpassagen", "Starkes Abenteuergefühl"],
    whyChoose: ["Direktester Weg zum Gipfel", "Für erfahrene Trekker geeignet", "Ruhiger als andere Routen", "Spektakuläre Gratblicke"],
    itinerary: [
      { day: "Tag 1", title: "Umbwe Gate nach Umbwe Cave Camp", description: "Steiler Anstieg durch dichten Regenwald bis zur Umbwe Cave." },
      { day: "Tag 2", title: "Umbwe Cave nach Barranco", description: "Weitere steile Etappe entlang des Grats mit dramatischen Ausblicken." },
      { day: "Tag 3", title: "Barranco nach Karanga", description: "Aufstieg über die Barranco Wall und weiter nach Karanga." },
      { day: "Tag 4", title: "Karanga nach Barafu", description: "Ankunft im Barafu Camp und Vorbereitung für den nächtlichen Gipfelversuch." },
      { day: "Tag 5", title: "Gipfel und Mweka Camp", description: "Nachtaufstieg zum Uhuru Peak und Abstieg zum Mweka Camp." },
      { day: "Tag 6", title: "Mweka Camp nach Mweka Gate", description: "Letzter Abstieg durch den Regenwald und Rückkehr zum Hotel." },
    ],
  },
  "shira-route": {
    title: "Shira-Route",
    headline: "7 Tage Shira-Route - Westlicher Kilimandscharo-Trek",
    location: "Kilimandscharo-Nationalpark, Tansania",
    duration: "7 Tage",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Juni - Oktober und Januar - März",
    permits: "Permits für den Kilimandscharo-Nationalpark erforderlich",
    description: "Eine landschaftlich schöne Westroute, die hoch auf dem Shira-Plateau beginnt und gute Akklimatisation bietet.",
    overview: "Die Shira-Route startet in großer Höhe auf der Westseite des Kilimandscharo. Sie eröffnet schnell weite Ausblicke und schließt später an Machame und Lemosho an.",
    priceFrom: "2.300 $ pro Person",
    highlights: ["Panoramareiche Querung des Shira-Plateaus", "Abgelegener Start im Westen", "Starke Landschaftserlebnisse", "Gute Gipfelerfolgsquote", "Wenig Andrang zu Beginn"],
    whyChoose: ["Frühe Hochgebirgslandschaften", "Gutes Akklimatisationspotenzial", "Wunderschöne Plateau-Panoramen", "Ruhiger westlicher Anstieg"],
    itinerary: [
      { day: "Tag 1", title: "Shira Gate nach Shira 1", description: "Start in großer Höhe durch Moorlandschaft bis zum Shira 1 Camp." },
      { day: "Tag 2", title: "Shira 1 nach Shira 2", description: "Leichte Wanderung über das Plateau mit Blick auf Kibo und Mount Meru." },
      { day: "Tag 3", title: "Shira 2 nach Barranco über Lava Tower", description: "Aufstieg zur Lava Tower und Abstieg nach Barranco." },
      { day: "Tag 4", title: "Barranco nach Karanga", description: "Barranco Wall und Weiterweg zum Karanga Camp." },
      { day: "Tag 5", title: "Karanga nach Barafu", description: "Ankunft im Barafu Camp und Vorbereitung auf den Gipfeltag." },
      { day: "Tag 6", title: "Gipfel und Mweka Camp", description: "Nachtaufstieg zum Uhuru Peak und Abstieg nach Mweka." },
      { day: "Tag 7", title: "Mweka Camp nach Mweka Gate", description: "Abstieg durch üppigen Regenwald bis zum Gate." },
    ],
  },
  "mount-meru-trek": {
    title: "Mount-Meru-Trek",
    headline: "4 Tage Mount Meru Trek - Arusha-Nationalpark",
    location: "Arusha-Nationalpark, Tansania",
    duration: "4 Tage",
    elevation: "4.566 m (Socialist Peak)",
    bestTime: "Juni - Oktober und Januar - Februar",
    permits: "Parkgebühren und bewaffneter Ranger erforderlich",
    description: "Der zweithöchste Berg Tansanias und ein hervorragender Akklimatisationstrek vor dem Kilimandscharo.",
    overview: "Der Mount-Meru-Trek ist ein spektakuläres 4-Tage-Abenteuer im Arusha-Nationalpark. Er verbindet Tierbeobachtungen an den unteren Hängen mit einem eindrucksvollen Gipfelanstieg entlang des Kraterrands.",
    priceFrom: "1.000 $ pro Person",
    highlights: ["Wildtierbeobachtungen an den unteren Hängen", "Spektakuläre Blicke am Kraterrand", "Perfekte Akklimatisation vor dem Kilimandscharo", "Weniger überlaufen", "Wunderschöner Gipfel bei Sonnenaufgang"],
    whyChoose: ["Ausgezeichnete Vorbereitung für den Kilimandscharo", "Reiche Tierwelt mit Büffeln und Giraffen", "Dramatische Vulkanlandschaft", "Kürzer und günstiger als der Kilimandscharo"],
    itinerary: [
      { day: "Tag 1", title: "Momella Gate nach Miriakamba Hut", description: "Trekking durch Wald und Grasland mit Tiersichtungen bis zur Miriakamba Hut." },
      { day: "Tag 2", title: "Miriakamba Hut nach Saddle Hut", description: "Steilerer Aufstieg mit Panorama auf Krater und Kilimandscharo." },
      { day: "Tag 3", title: "Gipfeltag und zurück zur Miriakamba Hut", description: "Nachtaufstieg zum Socialist Peak und anschließender Abstieg." },
      { day: "Tag 4", title: "Miriakamba Hut nach Momella Gate", description: "Letzter Abstieg durch den Arusha-Nationalpark und Rückfahrt nach Arusha." },
    ],
  },
  "ol-doinyo-lengai-night-hike": {
    title: "Ol Doinyo Lengai Nachtwanderung",
    headline: "Aktive Besteigung des Vulkans Ol Doinyo Lengai",
    location: "Lake Natron, Tansania",
    duration: "1 Nacht",
    elevation: "2.962 m",
    bestTime: "Juni - Oktober",
    permits: "Lokaler Guide erforderlich",
    description: "Besteigen Sie Tansanias einzigen aktiven Vulkan in der Nacht und erleben Sie dramatische Sonnenaufgangsblicke über das Rift Valley.",
    overview: "Ol Doinyo Lengai ist Tansanias einziger aktiver Vulkan und für die Massai ein heiliger Berg. Diese anspruchsvolle Nachtbesteigung belohnt mit eindrucksvollen Panoramen auf Rift Valley, Lake Natron und Kilimandscharo.",
    priceFrom: "350 $ pro Person",
    highlights: ["Aktive Vulkanbesteigung", "Sonnenaufgang am Gipfel", "Massai-Kulturregion", "Anspruchsvolles Abenteuer", "Abgelegene Wildnis"],
  },
  "packing-list": {
    title: "Kilimandscharo-Packliste",
    headline: "Wichtige Packliste für den Kilimandscharo",
    location: "Mount Kilimanjaro, Tansania",
    duration: "Vorbereitungsleitfaden",
    elevation: "Bis 5.895 m",
    bestTime: "Ganzjährig",
    permits: "Für diesen Leitfaden nicht erforderlich",
    description: "Vollständige Ausrüstungsliste für eine sichere und komfortable Kilimandscharo-Besteigung.",
    overview: "Die Vorbereitung auf den Kilimandscharo erfordert passende Kleidung, ein gutes Schichtsystem, geeignete Schlafausrüstung und persönliche Essentials. Die richtige Ausrüstung erhöht Komfort und Gipfelchancen deutlich.",
    highlights: ["Mehrschichtiges Kleidungssystem", "Hochgebirgs-Schlafsack", "Wasserdichte Ausrüstung", "Geeignete Wanderschuhe", "Stirnlampe und Trekkingstöcke"],
  },
  "altitude-acclimatization": {
    title: "Höhe und Akklimatisation",
    headline: "Höhenanpassung am Kilimandscharo verstehen",
    location: "Mount Kilimanjaro",
    duration: "Vorbereitungsleitfaden",
    elevation: "5.895 m",
    bestTime: "Ganzjährig",
    permits: "Nicht erforderlich",
    description: "Erfahren Sie, wie gute Akklimatisation Ihre Chancen erhöht, den Uhuru Peak sicher zu erreichen.",
    overview: "Die Höhenkrankheit ist die größte Herausforderung am Kilimandscharo. Längere Routen, gute Hydration und ruhiges Tempo verbessern die Erfolgsquote deutlich.",
    highlights: ["Prinzip 'hoch steigen, tief schlafen'", "Wichtigkeit der Hydration", "Strategie des langsamen Aufstiegs", "Beobachtung von AMS-Symptomen"],
  },
  "best-time-to-climb": {
    title: "Beste Reisezeit für den Kilimandscharo",
    headline: "Saisonaler Leitfaden für die Kilimandscharo-Besteigung",
    location: "Mount Kilimanjaro",
    duration: "Vorbereitungsleitfaden",
    elevation: "5.895 m",
    bestTime: "Januar-März und Juni-Oktober",
    permits: "Nicht erforderlich",
    description: "Saisonale Übersicht zu Wetterbedingungen und Gipfelverhältnissen am Kilimandscharo.",
    overview: "Der Kilimandscharo kann das ganze Jahr über bestiegen werden, doch die Trockenzeiten bieten meist bessere Sicht und sicherere Bedingungen am Gipfel.",
    highlights: ["Vorteile der Trockenzeit", "Aspekte der Regenzeit", "Erwartbare Temperaturen", "Besucherzahlen nach Monaten"],
  },
  "climbing-faqs": {
    title: "Kilimandscharo-Besteigung FAQs",
    headline: "Häufige Fragen zum Kilimandscharo",
    location: "Mount Kilimanjaro",
    duration: "Informationsleitfaden",
    elevation: "5.895 m",
    bestTime: "Ganzjährig",
    permits: "Nicht erforderlich",
    description: "Häufige Fragen zur Kilimandscharo-Besteigung, beantwortet von unseren Bergexperten.",
    overview: "Hier finden Sie klare Antworten zu Fitness, Training, Sicherheit, Höhenkrankheit, Gipfelerfolgsraten und der Vorbereitung Ihrer Expedition.",
    highlights: ["Brauche ich Vorerfahrung?", "Wie fit sollte ich sein?", "Wie hoch ist die Gipfelerfolgsrate?", "Wie kalt wird es?"],
  },
  "udzungwa-mountains-waterfalls-hike": {
    title: "Udzungwa Mountains Wasserfallwanderung",
    headline: "Regenwald- und Wasserfall-Trek in Udzungwa",
    location: "Udzungwa-Mountains-Nationalpark",
    duration: "1-3 Tage",
    elevation: "Bis 2.576 m",
    bestTime: "Juni - Oktober",
    permits: "Parkgebühren erforderlich",
    description: "Wanderung im tropischen Regenwald mit spektakulären Wasserfällen und endemischer Tierwelt.",
    highlights: ["Sanje-Wasserfälle", "Regenwald-Biodiversität", "Angenehmes Klima", "Endemische Tierwelt", "Fotomöglichkeiten"],
  },
  "usambara-mountains-cultural-walks": {
    title: "Kulturelle Wanderungen in den Usambara-Bergen",
    headline: "Dorf- und Kulturwanderungen",
    location: "Lushoto, Tansania",
    duration: "1-4 Tage",
    elevation: "1.200 m - 2.300 m",
    bestTime: "Juni - Oktober",
    permits: "Lokaler Guide empfohlen",
    description: "Entspanntes Trekking im Hochland durch Dörfer und zu malerischen Aussichtspunkten.",
    highlights: ["Dorfwanderungen", "Angenehme Temperaturen", "Kulturelle Begegnungen", "Schöne Ausblicke", "Familienfreundlich"],
  },
  "ngorongoro-highlands-empakaai-crater-trek": {
    title: "Empakaai-Krater-Trek",
    headline: "Walking Safari im Ngorongoro-Hochland",
    location: "Ngorongoro Conservation Area",
    duration: "1-2 Tage",
    elevation: "3.200 m",
    bestTime: "Juni - Oktober, Januar - März",
    permits: "Naturschutzgebühren erforderlich",
    description: "Geführte Kraterrand-Wanderung im Ngorongoro-Hochland mit Blick auf den Flamingosee.",
    highlights: ["Vulkanlandschaften", "Blick auf den Flamingosee", "Massai-Landschaften", "Hochland-Trekking", "Perfekt als Safari-Verlängerung"],
  },
}

export const deLocalizedOverlays = {
  safaris: deSafariOverlays,
  dayTrips: deDayTripOverlays,
  zanzibar: deZanzibarOverlays,
  adventures: deAdventureOverlays,
  destinations: deDestinationOverlays,
  treks: deTrekOverlays,
}
