import type { Adventure } from "@/lib/adventures-data"
import type { DayTrip } from "@/lib/day-trips-data"
import type { Destination } from "@/lib/destinations-data"
import type { SafariPackage } from "@/lib/safaris-data"
import type { Trek } from "@/lib/treks-data"
import type { ZanzibarExperience } from "@/lib/zanzibar-experiences"

export const esSafariOverlays: Record<string, Partial<SafariPackage>> = {
  "big-five": {
    title: "Safari Big Five de 3 días",
    region: "Norte de Tanzania",
    duration: "3 días",
    price: "Desde 1.200 $",
    description:
      "Safari corto ideal para una primera visita, con el objetivo de observar los Big Five en Tarangire y el lago Manyara.",
    highlights: [
      "Fauna de los Big Five",
      "Elefantes de Tarangire",
      "Paisajes del lago Manyara",
      "Vehículo privado 4x4",
      "Excelente relación calidad-precio",
    ],
    itinerary: [
      { day: 1, title: "Arusha - Tarangire", description: "Traslado al parque nacional de Tarangire con safari por la tarde." },
      { day: 2, title: "Día completo en Tarangire", description: "Safari de día entero centrado en elefantes y leones." },
      { day: 3, title: "Lago Manyara y regreso", description: "Mañana en el lago Manyara y regreso a Arusha." },
    ],
    includes: ["Tarifas de parque", "Alojamiento", "Comidas", "Guía privado", "Vehículo 4x4"],
  },
  "big-five-short": {
    title: "Escapada Big Five de 3 días",
    region: "Norte de Tanzania",
    duration: "3 días",
    price: "Desde 1.200 $",
    description:
      "Safari intenso de 3 días centrado en los Big Five en los parques de Tarangire y el lago Manyara.",
    highlights: [
      "Itinerario compacto",
      "Enfoque en los Big Five",
      "Perfecto para una estancia corta",
      "Vehículo privado",
      "Guía experto",
    ],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Traslado y safari en el parque nacional de Tarangire." },
      { day: 2, title: "Día completo en Tarangire", description: "Observación prolongada de fauna en Tarangire." },
      { day: 3, title: "Lago Manyara", description: "Safari matutino y regreso a Arusha." },
    ],
    includes: ["Tarifas de parque", "Alojamiento", "Comidas", "Guía", "Transporte"],
  },
  "wonders-of-tanzania": {
    title: "Las maravillas de Tanzania en 6 días",
    region: "Norte de Tanzania",
    duration: "6 días",
    price: "Desde 2.800 $",
    description:
      "Safari completo que recorre Tarangire, el Serengeti y el cráter del Ngorongoro.",
    highlights: [
      "Llanuras del Serengeti",
      "Cráter del Ngorongoro",
      "Elefantes de Tarangire",
      "Lodges de categoría media",
      "Ritmo equilibrado",
    ],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Salida desde Arusha hacia el parque nacional de Tarangire." },
      { day: "2-3", title: "Serengeti", description: "Safaris en el parque nacional del Serengeti." },
      { day: "4-5", title: "Ngorongoro", description: "Descenso al cráter y observación de fauna." },
      { day: 6, title: "Regreso", description: "Regreso a Arusha." },
    ],
    includes: ["Todas las tarifas de parque", "Alojamiento", "Pensión completa", "Guía privado", "Land Cruiser 4x4"],
  },
  "bush-and-beach": {
    title: "Safari de lujo bush y playa de 8 días",
    region: "Norte de Tanzania y Zanzíbar",
    duration: "8 días",
    price: "Desde 5.400 $",
    description:
      "Combine un safari de lujo en el Serengeti y el Ngorongoro con una estancia relajante en las playas de Zanzíbar.",
    highlights: [
      "Safari por el circuito norte",
      "Extensión playera en Zanzíbar",
      "Visita a Stone Town",
      "Lodges de lujo",
      "Traslados privados",
    ],
    itinerary: [
      { day: "1-5", title: "Circuito norte", description: "Safari en Tarangire, Serengeti y Ngorongoro." },
      { day: 6, title: "Vuelo a Zanzíbar", description: "Traslado a su resort playero en Zanzíbar." },
      { day: 7, title: "Playa y cultura", description: "Opciones de visita a Stone Town y tour de especias." },
      { day: 8, title: "Salida", description: "Mañana en la playa y traslado al aeropuerto." },
    ],
    includes: ["Logística de safari", "Vuelo doméstico a Zanzíbar", "Hotel de playa", "Excursiones seleccionadas", "Guía privado"],
  },
  "great-migration-safari": {
    title: "Safari Gran Migración en el Serengeti",
    region: "Norte de Tanzania",
    duration: "8 días",
    price: "Desde 4.600 $",
    description:
      "Asista a uno de los mayores espectáculos naturales del mundo: la Gran Migración de ñus.",
    highlights: [
      "Cruces del río Mara",
      "Observación de los Big Five",
      "Vehículo privado 4x4",
      "Campamentos de lujo en tienda",
    ],
    itinerary: [
      { day: 1, title: "Llegada a Arusha", description: "Traslado a su lodge para una sesión informativa." },
      { day: "2-3", title: "Serengeti central", description: "Safaris en el corazón del territorio de los grandes felinos." },
      { day: "4-6", title: "Serengeti norte", description: "Seguimiento de manadas cerca del río Mara." },
      { day: 7, title: "Cráter del Ngorongoro", description: "Descenso a este jardín del Edén africano." },
      { day: 8, title: "Salida", description: "Regreso a Arusha para su vuelo de retorno." },
    ],
    includes: ["Todas las tarifas de parque", "Guía privado", "Pensión completa", "Land Cruiser 4x4"],
  },
  "private-tours": {
    title: "Safaris privados a medida",
    region: "Toda Tanzania",
    duration: "A medida",
    price: "Precio bajo consulta",
    description:
      "Itinerarios exclusivos diseñados para parejas, familias o grupos pequeños que buscan flexibilidad total.",
    highlights: [
      "Guía privado dedicado",
      "Programa diario personalizado",
      "Lodges cuidadosamente seleccionados",
      "4x4 privado",
    ],
    itinerary: [
      { day: "Nota", title: "Días personalizables", description: "Diseñamos el itinerario según sus intereses y su ritmo." },
    ],
    includes: ["Transporte privado", "Guía naturalista experto", "Planificación personalizada"],
  },
  "safari-vehicles": {
    title: "Nuestros Land Cruisers 4x4 para safari",
    region: "Logística",
    duration: "Especificaciones técnicas",
    price: "Incluido en los circuitos",
    description:
      "Nuestra flota está compuesta por Land Cruisers 4x4 especialmente adaptados para los terrenos exigentes de Tanzania.",
    highlights: [
      "Techo abatible con vista de 360°",
      "Puntos de carga a bordo",
      "Nevera para bebidas frías",
      "Radio de largo alcance",
    ],
    itinerary: [
      { day: "Confort", title: "Espacio y visibilidad", description: "Chasis alargados para mayor espacio para las piernas y amplios ventanales panorámicos." },
      { day: "Seguridad", title: "Mantenimiento", description: "Cada vehículo se revisa después de cada safari." },
    ],
    includes: ["Asiento junto a la ventana garantizado", "Snorkel para vadeos", "Guías de campo y prismáticos"],
  },
  "packing-list": {
    title: "Lo esencial en la maleta para safari",
    region: "Preparación",
    duration: "Lista de verificación",
    price: "Guía experto",
    description:
      "Asegúrese de llevar todo lo necesario para una aventura cómoda y segura en plena sabana.",
    highlights: [
      "Ropa de colores neutros",
      "Protección solar",
      "Prismáticos de calidad",
      "Tratamiento antipalúdico",
    ],
    itinerary: [
      { day: "Ropa", title: "Qué llevar", description: "Las capas son esenciales. Mañanas frescas, tardes calurosas. Evite el azul y el negro por las moscas tsetsé." },
      { day: "Equipo", title: "Tecnología esencial", description: "Cámara, baterías de repuesto y power banks son imprescindibles en zonas remotas." },
    ],
    includes: ["Lista de verificación estándar", "Requisitos de visado", "Consejos de salud"],
  },
  "honeymoon-safari": {
    title: "Safaris románticos de luna de miel",
    region: "Tanzania romántica",
    duration: "7 a 12 días",
    price: "Desde 5.200 $",
    description:
      "Combine la emoción de la vida salvaje con un lujo íntimo en los entornos más románticos de África.",
    highlights: [
      "Cenas privadas en la sabana",
      "Noches en star-bed",
      "Extensiones a Zanzíbar",
      "Safari en globo aerostático",
    ],
    itinerary: [
      { day: "Ambiente", title: "Lujo íntimo", description: "Seleccionamos pequeños campamentos aislados que priorizan la intimidad y el romanticismo." },
    ],
    includes: ["Masaje en pareja", "Aperitivos con champán al atardecer", "Traslados privados"],
  },
}

export const esDayTripOverlays: Record<string, Partial<DayTrip>> = {
  "chemka-hot-springs": {
    title: "Excursión a Chemka Hot Springs",
    shortTitle: "Chemka Hot Springs",
    description:
      "Escápese a las aguas cristalinas de Chemka Hot Springs, un paraíso natural al pie del Kilimanjaro. Disfrute de un baño refrescante, relájese en las orillas arenosas y descubra aguas termales ricas en minerales.",
    highlight: "Baño en aguas termales naturales cristalinas",
    duration: "Día completo",
    location: "Kikuletwa, Kilimanjaro",
    highlights: [
      "Baño en aguas termales naturales cristalinas",
      "Relajación en playas de arena",
      "Almuerzo tradicional junto al agua",
      "Ruta panorámica por plantaciones de café",
      "Excelentes oportunidades fotográficas",
    ],
    included: ["Tarifas de entrada", "Guía profesional", "Transporte privado", "Almuerzo local", "Agua potable"],
    notIncluded: ["Gastos personales", "Propinas", "Seguro de viaje"],
    itinerary: [
      { time: "07:00", activity: "Recogida en su hotel en Arusha" },
      { time: "08:30", activity: "Ruta panorámica hacia Chemka a través de plantaciones de café" },
      { time: "09:30", activity: "Llegada a Chemka Hot Springs y cambio de ropa" },
      { time: "10:00", activity: "Baño y relajación en las pozas naturales" },
      { time: "12:30", activity: "Almuerzo servido junto a la poza" },
      { time: "14:00", activity: "Tiempo libre para nadar y explorar" },
      { time: "15:30", activity: "Salida hacia Arusha" },
      { time: "17:00", activity: "Regreso a su hotel" },
    ],
  },
  "lake-duluti": {
    title: "Excursión al lago Duluti",
    shortTitle: "Lago Duluti",
    description:
      "Descubra la belleza tranquila del lago Duluti, un espectacular lago de cráter situado a las afueras de Arusha. Paseo guiado por el bosque, observación de aves y salida en canoa por aguas tranquilas.",
    highlight: "Paseo en canoa por un pintoresco lago de cráter",
    duration: "Medio día / día completo",
    location: "Arusha",
    highlights: [
      "Paseo guiado por el bosque alrededor del lago",
      "Canoa en el lago de cráter",
      "Observación de más de 200 especies de aves",
      "Picnic junto al lago",
      "Encuentro cultural con comunidades locales",
    ],
    included: ["Tarifas de entrada", "Guía profesional", "Transporte privado", "Alquiler de canoa", "Almuerzo (día completo)", "Agua potable"],
    notIncluded: ["Gastos personales", "Propinas", "Seguro de viaje"],
    itinerary: [
      { time: "08:00", activity: "Recogida en su hotel en Arusha" },
      { time: "09:00", activity: "Llegada al lago Duluti y encuentro con su guía" },
      { time: "09:30", activity: "Paseo guiado alrededor del cráter" },
      { time: "11:00", activity: "Salida en canoa por el lago Duluti" },
      { time: "12:30", activity: "Picnic junto al lago" },
      { time: "14:00", activity: "Observación de aves y fotografía" },
      { time: "15:30", activity: "Salida hacia Arusha" },
      { time: "16:30", activity: "Regreso a su hotel" },
    ],
  },
  "arusha-town-tour": {
    title: "Visita de la ciudad de Arusha",
    shortTitle: "Visita de Arusha",
    description:
      "Descubra Arusha con un guía local: sitios patrimoniales, mercados animados y la vibrante vida cotidiana de la capital del safari en Tanzania.",
    highlight: "Paseo cultural guiado por Arusha",
    duration: "Medio día",
    location: "Arusha",
    highlights: [
      "Sitios emblemáticos del centro de Arusha",
      "Historia y cultura local",
      "Visitas a mercados",
      "Paradas de artesanía y souvenirs",
      "Ritmo privado y flexible",
    ],
    included: ["Guía profesional", "Transporte privado", "Agua embotellada"],
    notIncluded: ["Comidas", "Compras personales", "Propinas"],
    itinerary: [
      { time: "09:00", activity: "Recogida en el hotel en Arusha" },
      { time: "09:30", activity: "Visita a pie del centro de Arusha" },
      { time: "11:00", activity: "Descubrimiento de sitios culturales y mercados" },
      { time: "12:30", activity: "Sugerencia de almuerzo opcional" },
      { time: "13:30", activity: "Regreso al hotel" },
    ],
  },
  "curios-gift-shops": {
    title: "Tour de tiendas de artesanía y regalos",
    shortTitle: "Artesanía y regalos",
    description:
      "Recorra las mejores tiendas de Arusha y los talleres de artesanos para descubrir cuentas masái, pinturas Tinga Tinga, esculturas y souvenirs hechos a mano.",
    highlight: "Artesanía y regalos auténticos de Tanzania",
    duration: "Medio día",
    location: "Arusha",
    highlights: [
      "Talleres de artesanos",
      "Tiendas de comercio justo",
      "Cuentas masái",
      "Arte Tinga Tinga",
      "Asesoramiento de envío disponible",
    ],
    included: ["Guía", "Transporte entre tiendas", "Agua embotellada"],
    notIncluded: ["Compras", "Gastos de envío", "Propinas"],
    itinerary: [
      { time: "09:00", activity: "Recogida e información inicial" },
      { time: "09:30", activity: "Visita a tiendas y talleres seleccionados" },
      { time: "12:00", activity: "Tiempo libre para compras" },
      { time: "13:00", activity: "Regreso al hotel" },
    ],
  },
  "local-markets": {
    title: "Visita de mercados locales",
    shortTitle: "Mercados locales",
    description:
      "Viva el ambiente colorido de los mercados de Arusha: productos frescos, especias, telas y el ritmo cotidiano de la vida local tanzana.",
    highlight: "Inmersión en el corazón de los mercados locales",
    duration: "Medio día",
    location: "Arusha",
    highlights: [
      "Paseo por el mercado central",
      "Especias y productos frescos",
      "Textiles y artesanía",
      "Degustaciones de especialidades locales",
      "Experiencia ideal para fotografía",
    ],
    included: ["Guía local", "Visita al mercado", "Transporte", "Agua"],
    notIncluded: ["Compras de alimentos", "Compras personales", "Propinas"],
    itinerary: [
      { time: "08:30", activity: "Recogida por la mañana" },
      { time: "09:00", activity: "Visita guiada de los principales pabellones del mercado" },
      { time: "11:00", activity: "Sección de especias y productos frescos" },
      { time: "12:00", activity: "Regreso al hotel" },
    ],
  },
}

export const esZanzibarOverlays: Record<string, Partial<ZanzibarExperience>> = {
  "spice-tours": {
    title: "Tours de especias en Zanzíbar",
    description:
      "Pasee por las fragantes plantaciones de Zanzíbar y descubra cómo el clavo, la vainilla, la canela y la nuez moscada han moldeado la historia y la cocina de la isla.",
    highlight: "Experiencia inmersiva en una finca de especias",
    duration: "Medio día",
    price: "Desde 45 $ por persona",
    highlights: [
      "Paseo guiado por una plantación de especias",
      "Degustación de frutas tropicales frescas",
      "Descubrimiento de los usos tradicionales de las especias",
      "Opción de almuerzo local disponible",
      "Perfecto después de un safari",
    ],
    included: ["Recogida en Stone Town", "Guía profesional", "Entrada a la finca de especias", "Degustación de frutas"],
    itinerary: [
      { step: "Recogida por la mañana", detail: "Traslado desde su hotel o Stone Town hacia una finca de especias en activo." },
      { step: "Visita a la plantación", detail: "Paseo guiado para identificar especias, hierbas y frutas tropicales." },
      { step: "Degustación y compras", detail: "Pruebe productos frescos y descubra artículos artesanales a base de especias." },
      { step: "Regreso", detail: "Regreso a su hotel o continuación hacia la playa." },
    ],
  },
  "cultural-tour": {
    title: "Visita cultural de Stone Town",
    description:
      "Explore Stone Town, Patrimonio de la Humanidad por la UNESCO, con un guía local: puertas talladas, callejones históricos, mercados y la vibrante cultura suajili.",
    highlight: "Paseo patrimonial por Stone Town",
    duration: "Medio día",
    price: "Desde 40 $ por persona",
    highlights: [
      "Visita histórica a pie de Stone Town",
      "Fuerte antiguo y sector House of Wonders",
      "Mercados locales y talleres artesanales",
      "Arquitectura suajili y puertas talladas",
      "Ritmo flexible para fotógrafos",
    ],
    included: ["Guía local profesional", "Visita a pie de Stone Town", "Agua embotellada"],
    itinerary: [
      { step: "Encuentro con su guía", detail: "Salida desde un punto central de Stone Town o su hotel." },
      { step: "Paseo patrimonial", detail: "Visita de los principales monumentos, mercados y patios ocultos." },
      { step: "Paradas culturales", detail: "Descubrimiento de los legados árabe, persa, indio y africano de Zanzíbar." },
      { step: "Tiempo libre", detail: "Sugerencia de almuerzo y regreso a su hotel." },
    ],
  },
  "diving-snorkeling": {
    title: "Buceo y snorkel en Zanzíbar",
    description:
      "Descubra el atolón de Mnemba y los arrecifes de coral de Zanzíbar en excursiones guiadas de snorkel o buceo, con equipo y traslados en barco incluidos.",
    highlight: "Arrecifes cristalinos del océano Índico",
    duration: "Día completo",
    price: "Desde 85 $ por persona",
    highlights: [
      "Salida en barco hacia los sitios de arrecife",
      "Equipo de snorkel proporcionado",
      "Observación de delfines según la temporada",
      "Almuerzo ligero en banco de arena",
      "Opciones de buceo PADI bajo consulta",
    ],
    included: ["Traslado en barco", "Equipo de snorkel", "Guía", "Almuerzo ligero", "Bebidas"],
    itinerary: [
      { step: "Recogida en el hotel", detail: "Traslado matutino hacia la playa de salida." },
      { step: "Excursión en barco", detail: "Navegación hacia Mnemba o los arrecifes de la costa norte." },
      { step: "Sesiones de snorkel", detail: "Varias paradas para explorar los arrecifes y nadar." },
      { step: "Regreso", detail: "Regreso por la tarde a su hotel playero." },
    ],
  },
  transfers: {
    title: "Traslados de aeropuerto y ferry en Zanzíbar",
    description:
      "Traslados privados fiables entre el aeropuerto internacional Abeid Amani Karume, las terminales de ferry, Stone Town y los resorts playeros de Zanzíbar.",
    highlight: "Traslados insulares puerta a puerta",
    duration: "Bajo consulta",
    price: "Desde 35 $ por vehículo",
    highlights: [
      "Recepción personalizada en el aeropuerto",
      "Traslados desde terminales de ferry",
      "Conexiones entre resorts y Stone Town",
      "Seguimiento de vuelos incluido",
      "Asistencia 24/7 de Gladiolus Tours",
    ],
    included: ["Vehículo privado", "Conductor de habla inglesa", "Agua embotellada", "Seguimiento de vuelos y ferries"],
    itinerary: [
      { step: "Reserva", detail: "Comparta los detalles de su vuelo o ferry al confirmar." },
      { step: "Recepción", detail: "El conductor le espera con un cartel con su nombre." },
      { step: "Traslado directo", detail: "Viaje cómodo hacia su hotel o el puerto." },
      { step: "Opción de regreso", detail: "Reserve también su traslado de salida." },
    ],
  },
}

export const esAdventureOverlays: Record<string, Partial<Adventure>> = {
  "kilimanjaro-northern-circuit": {
    title: "Trek de 9 días al Kilimanjaro por el Northern Circuit",
    category: "Ascenso en montaña",
    description:
      "El Northern Circuit es la ruta más panorámica del Kilimanjaro con una excelente aclimatación. Espere crestas alpinas aisladas, vistas de glaciares y un ritmo de ascenso progresivo.",
    highlights: [
      "La ventana de aclimatación más larga para maximizar las posibilidades de cumbre",
      "Laderas norte con menos senderistas",
      "Equipo dedicado para la asistencia en la cumbre",
      "Opción de campamento privado en el cráter",
    ],
    itinerary: [
      { day: 1, title: "Llegada y revisión del equipo", description: "Llegada a Arusha, encuentro con su guía principal e información completa sobre equipo y seguridad." },
      { day: 2, title: "Lemosho Gate - Mti Mkubwa", description: "Trekking a través del bosque tropical hasta el primer campamento, con un ritmo de aclimatación progresivo." },
      { day: 3, title: "Exploración de la meseta de Shira", description: "Travesía de las landas abiertas con magníficas vistas de la meseta de Shira y las cumbres circundantes." },
      { day: 4, title: "Aclimatación en Lava Tower", description: "Ascenso hacia Lava Tower para aclimatación y descenso a un campamento más bajo para descansar." },
      { day: 5, title: "Travesía del Northern Circuit", description: "Travesía de la ladera norte, más tranquila, en medio de paisajes alpinos espectaculares." },
      { day: 6, title: "Campamento de altitud e información de cumbre", description: "Llegada al campamento de altitud, hidratación y preparación para el ascenso nocturno." },
      { day: 7, title: "Día de cumbre", description: "Ascenso nocturno hacia Uhuru Peak y descenso al campamento intermedio para recuperarse." },
      { day: 8, title: "Descenso hacia Mweka", description: "Descenso a través de landas y bosque tropical con sesión final de evaluación." },
      { day: 9, title: "Salida", description: "Traslado de regreso a Arusha o extensión de safari." },
    ],
    packages: [
      { name: "Northern Circuit clásico", duration: "9 días", price: "Desde 3.950 $", description: "Trek equilibrado con campamentos premium, equipo completo de guías y traslados privados.", includes: ["Tarifas de parque", "Pensión completa", "Tiendas privadas", "Certificados de cumbre"] },
      { name: "Northern Circuit + safari", duration: "12 días", price: "Desde 5.900 $", description: "Añada tres días de safari en Tarangire y Ngorongoro después de la cumbre.", includes: ["Estancias en lodge de safari", "Vehículo 4x4", "Safari en pensión completa", "Tarifas de parque"] },
    ],
  },
  "walking-safaris": {
    title: "Safaris a pie y encuentros con guías indígenas",
    category: "Safaris a pie",
    description:
      "Tómese el tiempo de explorar a pie con guardaparques especializados y guías indígenas. Siga las huellas de la fauna, aprenda técnicas de supervivencia en la sabana y disfrute de aperitivos íntimos en plena naturaleza.",
    highlights: [
      "Seguimiento de huellas y aprendizaje de bushcraft",
      "Itinerarios de caminata de bajo impacto",
      "Aperitivos al atardecer junto al río",
      "Veladas de cuentos comunitarios",
    ],
    itinerary: [
      { day: 1, title: "Llegada e información del guardaparque", description: "Conozca a su equipo de guías y aprenda las normas de seguridad y los fundamentos del rastreo." },
      { day: 2, title: "Rastreo matutino y señales de fauna", description: "Siga huellas frescas y aprenda a identificar especies y sus hábitats." },
      { day: 3, title: "Inmersión con guías indígenas", description: "Pase tiempo con guías indígenas para descubrir la ecología local y las tradiciones culturales." },
      { day: 4, title: "Caminata junto al río y sundowner", description: "Explore los corredores fluviales y relájese con un aperitivo refinado junto al río." },
      { day: 5, title: "Salida o safari complementario", description: "Traslado a la siguiente etapa de su viaje o extensión en safari en vehículo." },
    ],
    packages: [
      { name: "Esenciales del safari a pie", duration: "5 días", price: "Desde 2.150 $", description: "Caminatas guiadas con lodges boutique e informes diarios.", includes: ["Permisos de caminata", "Guardaparque experto", "Todas las comidas", "Traslados"] },
      { name: "Caminata + fly camp", duration: "6 días", price: "Desde 2.950 $", description: "Incluye una noche bajo las estrellas con un equipo de fly camp.", includes: ["Instalación del fly camp", "Chef privado", "Vigilante nocturno", "Lodges de lujo"] },
    ],
  },
  "zanzibar-coast": {
    title: "Costa de Zanzíbar y cultura de las especias",
    category: "Estancia playera",
    description:
      "Relájese en la costa de las especias con visitas a Stone Town, cruceros en dhow y estancias boutique que combinan cultura y bienestar.",
    highlights: [
      "Paseos patrimoniales por Stone Town",
      "Tour privado de una finca de especias",
      "Navegación en dhow al atardecer",
      "Spa y bienestar",
    ],
    itinerary: [
      { day: 1, title: "Llegada a Stone Town", description: "Instalación en un hotel patrimonial y descubrimiento gastronómico guiado por la noche." },
      { day: 2, title: "Finca de especias y cultura", description: "Visita a una plantación de especias y sitios culturales con un guía historiador." },
      { day: 3, title: "Traslado a la playa", description: "Instalación en la costa para disfrutar de la playa, el snorkel y el spa." },
      { day: 4, title: "Experiencias oceánicas", description: "Crucero privado en dhow, snorkel en arrecife y cena de mariscos." },
      { day: 5, title: "Salida", description: "Mañana libre y traslado al aeropuerto." },
    ],
    packages: [
      { name: "Escapada a la costa de las especias", duration: "5 días", price: "Desde 1.900 $", description: "Hotel patrimonial y retiro playero con experiencias seleccionadas.", includes: ["Guía de Stone Town", "Resort de playa", "Traslados al aeropuerto", "Desayunos"] },
      { name: "Romance en la costa", duration: "6 días", price: "Desde 2.450 $", description: "Añada cenas privadas, rituales de spa y navegación al atardecer.", includes: ["Cena privada con chef", "Tratamientos de spa", "Crucero en dhow", "Servicio de mayordomo"] },
    ],
  },
  "northern-circuit-adventure": {
    title: "Safaris de aventura en el circuito norte",
    category: "Safaris de aventura",
    description:
      "Combine safaris en vehículo y actividades dinámicas: canoa, ciclismo, caminatas por el borde del cráter y jornadas fotográficas adaptadas a la mejor temporada de fauna.",
    highlights: [
      "Safaris en canoa en el lago Manyara",
      "Caminatas por el borde del cráter",
      "Sesiones de coaching fotográfico",
      "4x4 privado con itinerario flexible",
    ],
    itinerary: [
      { day: 1, title: "Llegada y orientación en Arusha", description: "Sesión de bienvenida con su director de safari y preparación del equipo." },
      { day: 2, title: "Safaris en Tarangire", description: "Salidas por la mañana y al atardecer con excursión en bicicleta opcional." },
      { day: 3, title: "Canoa en el lago Manyara", description: "Safari en canoa y encuentros culturales en el pueblo." },
      { day: 4, title: "Caminata por el borde del Ngorongoro", description: "Trekking guiado por el borde del cráter con almuerzo de picnic." },
      { day: 5, title: "Fotografía en el Serengeti", description: "Sesiones fotográficas en la hora dorada con guías expertos." },
      { day: 6, title: "Salida o extensión", description: "Extensión a Zanzíbar o salida por el aeropuerto del Kilimanjaro." },
    ],
    packages: [
      { name: "Aventura norte esencial", duration: "6 días", price: "Desde 3.200 $", description: "Safari activo con guía privado y ritmo diario flexible.", includes: ["Guía privado", "Campamentos de lujo", "Todas las comidas", "Tarifas de parque"] },
      { name: "Aventura norte + Zanzíbar", duration: "9 días", price: "Desde 4.850 $", description: "Añada tres días de playa en Zanzíbar y paradas culturales seleccionadas.", includes: ["Resort de playa", "Traslados en la isla", "Crucero en dhow", "Cena con chef"] },
    ],
  },
}

export const esDestinationOverlays: Record<string, Partial<Destination>> = {
  "serengeti-national-park": {
    title: "Parque nacional del Serengeti",
    location: "Tanzania",
    duration: "5 días",
    price: "Desde 2.500 $",
    description: "Descubra el famoso ecosistema del Serengeti, cuna de la Gran Migración y de una fauna abundante que incluye leones, leopardos, elefantes y guepardos.",
    highlights: ["Observar la Gran Migración", "Safari Big Five", "Vuelo en globo aerostático al amanecer", "Visita a aldeas masái", "Oportunidades de fotografía de fauna"],
    itinerary: [
      { day: 1, title: "Llegada y traslado al Serengeti", description: "Recepción en el aeropuerto del Kilimanjaro y traslado al Serengeti. Safari al atardecer." },
      { day: 2, title: "Día completo de safari", description: "Safaris por la mañana y por la tarde en el Serengeti central con almuerzo de picnic." },
      { day: 3, title: "Safari en globo aerostático", description: "Vuelo opcional al amanecer seguido de un desayuno con champán. Safari por la tarde." },
      { day: 4, title: "Experiencia cultural masái", description: "Visita a una aldea masái tradicional y safari al atardecer." },
      { day: 5, title: "Último safari y salida", description: "Safari matutino y regreso a Arusha." },
    ],
    included: ["Traslados al aeropuerto", "Alojamiento en campamento de lujo", "Todas las comidas durante el safari", "Guía profesional y vehículo 4x4", "Tarifas de parque", "Agua embotellada"],
    excluded: ["Vuelos internacionales", "Seguro de viaje", "Gastos personales", "Vuelo en globo aerostático (550 $)", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 8 personas",
  },
  "ngorongoro-crater": {
    title: "Cráter del Ngorongoro",
    location: "Tanzania",
    duration: "4 días",
    price: "Desde 2.000 $",
    description: "Explore la mayor caldera volcánica intacta del mundo, un santuario natural con una de las mayores densidades de fauna de África.",
    highlights: ["Safaris en el fondo del cráter", "Observación de rinocerontes negros", "Sitio arqueológico de Olduvai", "Vistas volcánicas espectaculares", "Flamencos del lago Magadi"],
    itinerary: [
      { day: 1, title: "Llegada y borde del cráter", description: "Traslado desde Arusha al Ngorongoro. Noche en lodge con vista al cráter." },
      { day: 2, title: "Safari en el fondo del cráter", description: "Descenso de 600 m para un día completo de safari con almuerzo de picnic." },
      { day: 3, title: "Olduvai Gorge y visita cultural", description: "Visita al sitio arqueológico y experiencia cultural masái." },
      { day: 4, title: "Salida", description: "Tiempo libre por la mañana y regreso a Arusha." },
    ],
    included: ["Todos los traslados", "Alojamiento en lodge", "Todas las comidas", "Tarifas y permisos del cráter", "Guía profesional", "Descenso al cráter"],
    excluded: ["Vuelos internacionales", "Bebidas alcohólicas", "Seguro de viaje", "Artículos personales", "Propinas"],
    bestTime: "Todo el año",
    groupSize: "2 a 6 personas",
  },
  "tarangire-national-park": {
    title: "Parque nacional de Tarangire",
    location: "Tanzania",
    duration: "3 días",
    price: "Desde 1.500 $",
    description: "Famoso por sus grandes manadas de elefantes y sus baobabs centenarios, Tarangire ofrece encuentros íntimos con la fauna en un entorno excepcional.",
    highlights: ["Grandes poblaciones de elefantes", "Baobabs ancestrales", "Leones trepadores", "Más de 550 especies de aves", "Safaris a pie disponibles"],
    itinerary: [
      { day: 1, title: "Arusha - Tarangire", description: "Ruta matutina hacia Tarangire y safari por la tarde." },
      { day: 2, title: "Día completo de safari", description: "Exploración del parque con almuerzo de picnic y opción de safari a pie." },
      { day: 3, title: "Safari matutino y regreso", description: "Último safari al amanecer y regreso a Arusha." },
    ],
    included: ["Transporte en 4x4", "Alojamiento en lodge", "Todas las comidas", "Tarifas de parque", "Guía profesional"],
    excluded: ["Vuelos internacionales", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 6 personas",
  },
  "lake-manyara-national-park": {
    title: "Parque nacional del lago Manyara",
    location: "Tanzania",
    duration: "2 días",
    price: "Desde 900 $",
    description: "Parque pequeño con hábitats variados, desde bosque alimentado por manantiales hasta lago alcalino, famoso por sus leones trepadores.",
    highlights: ["Leones trepadores", "Bandadas de flamencos en el lago", "Elefantes de bosque", "Pasarela en la copa de los árboles", "Aguas termales"],
    itinerary: [
      { day: 1, title: "Llegada y safari", description: "Traslado al lago Manyara y safari por la tarde en el bosque y a orillas del lago." },
      { day: 2, title: "Canopy walk y salida", description: "Pasarela matutina en la copa de los árboles, último safari y regreso a Arusha." },
    ],
    included: ["Todo el transporte", "Alojamiento en lodge", "Comidas", "Entrada al parque", "Servicios de guía"],
    excluded: ["Vuelos", "Seguro", "Artículos personales", "Propinas"],
    bestTime: "Todo el año",
    groupSize: "2 a 6 personas",
  },
  "mount-kilimanjaro-trek": {
    title: "Trek del monte Kilimanjaro",
    location: "Tanzania",
    duration: "8 días",
    price: "Desde 4.500 $",
    description: "Alcance el techo de África por la magnífica ruta Lemosho, reconocida por su excelente aclimatación y su alto índice de éxito.",
    highlights: ["Alcanzar Uhuru Peak a 5.895 m", "Atravesar múltiples zonas climáticas", "Vistas montañosas espectaculares", "Guías de montaña profesionales", "Alto índice de éxito en la cumbre"],
    itinerary: [
      { day: 1, title: "Londorossi Gate - Mti Mkubwa", description: "Trámites y caminata por el bosque tropical hasta el primer campamento." },
      { day: 2, title: "Mti Mkubwa - Shira 1", description: "Ascenso hacia la meseta de Shira a través de las landas." },
      { day: 3, title: "Shira 1 - Shira 2", description: "Día de aclimatación a través de la meseta de Shira." },
      { day: 4, title: "Shira 2 - Barranco", description: "Ascenso hasta Lava Tower y descenso para favorecer la aclimatación." },
      { day: 5, title: "Barranco - Karanga", description: "Ascenso del Barranco Wall y travesía hacia Karanga Camp." },
      { day: 6, title: "Karanga - Barafu", description: "Corta subida al campamento de altitud y preparación para la cumbre." },
      { day: 7, title: "Día de cumbre", description: "Salida nocturna hacia Uhuru Peak y descenso a Mweka Camp." },
      { day: 8, title: "Mweka - Gate", description: "Descenso final por el bosque y entrega de certificados." },
    ],
    included: ["Permisos de montaña", "Equipo de acampada", "Todas las comidas en la montaña", "Guías y porteadores profesionales", "Tarifas de rescate"],
    excluded: ["Vuelos internacionales", "Visado", "Seguro de viaje", "Equipo personal", "Propinas del equipo"],
    bestTime: "Enero-marzo, junio-octubre",
    groupSize: "2 a 12 personas",
  },
  "ruaha-national-park": {
    title: "Parque nacional de Ruaha",
    location: "Tanzania",
    duration: "4 días",
    price: "Desde 2.200 $",
    description: "Descubra el sur salvaje de Tanzania: paisajes fluviales, muy pocos vehículos y excelentes avistamientos de depredadores en el aislamiento de Ruaha.",
    highlights: ["Safaris lejos de las multitudes", "Excelentes avistamientos de leones y leopardos", "Observación de aves a lo largo del Gran Ruaha", "Caminatas guiadas en determinadas zonas", "Sundowners espectaculares en la sabana"],
    itinerary: [
      { day: 1, title: "Llegada en avión y safari al atardecer", description: "Llegada a la pista, instalación en el campamento y safari en la hora dorada." },
      { day: 2, title: "Día completo en Ruaha", description: "Safaris por la mañana y por la tarde entre lechos fluviales y llanuras arboladas con almuerzo en la sabana." },
      { day: 3, title: "Opción de safari a pie", description: "Caminata guiada opcional para rastreo y ecología seguida de safari por la tarde." },
      { day: 4, title: "Último safari y salida", description: "Safari matutino y traslado a la pista de aterrizaje." },
    ],
    included: ["Tarifas de parque", "Alojamiento", "Comidas", "Guía profesional", "Safaris", "Traslados a Ruaha"],
    excluded: ["Vuelos", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 6 personas",
  },
  "nyerere-national-park": {
    title: "Parque nacional de Nyerere",
    location: "Tanzania",
    duration: "3 días",
    price: "Desde 1.850 $",
    description: "Explore el ecosistema del río Rufiji con una combinación de safaris clásicos y aventuras acuáticas en una de las mayores áreas protegidas de África.",
    highlights: ["Safaris en barco por el Rufiji", "Muy buenos avistamientos de elefantes e hipopótamos", "Opciones de safari a pie", "Ritmo relajado con pocos vehículos", "Atardeceres espectaculares sobre el río"],
    itinerary: [
      { day: 1, title: "Llegada y crucero fluvial", description: "Llegada e instalación en el campamento y safari en barco al final de la tarde." },
      { day: 2, title: "Safaris en vehículo", description: "Safari matutino en las llanuras inundables y salida por la tarde hacia los puntos de agua." },
      { day: 3, title: "Actividad matutina y salida", description: "Pequeña caminata opcional o último safari y traslado a su conexión." },
    ],
    included: ["Alojamiento", "Comidas", "Tarifas de parque", "Safari en barco", "Safaris", "Servicios de guía"],
    excluded: ["Vuelos", "Seguro de viaje", "Compras personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 8 personas",
  },
  "zanzibar-island-escape": {
    title: "Escapada a la isla de Zanzíbar",
    location: "Tanzania",
    duration: "4 días",
    price: "Desde 1.300 $",
    description: "Termine su safari entre brisas marinas, cruceros en dhow y mañanas tranquilas en las playas de arena blanca de Zanzíbar.",
    highlights: ["Relajación junto al mar", "Descubrimiento de Stone Town", "Snorkel y excursiones a arrecifes", "Crucero en dhow al atardecer", "Cocina suajili y tours de especias"],
    itinerary: [
      { day: 1, title: "Llegada y playa", description: "Traslado a su hotel e instalación al ritmo de la isla con baño al atardecer." },
      { day: 2, title: "Stone Town y cultura", description: "Explore callejones y mercados de Stone Town y disfrute de una noche tranquila junto al mar." },
      { day: 3, title: "Excursión en el mar", description: "Snorkel, picnic en banco de arena o crucero según las condiciones y sus preferencias." },
      { day: 4, title: "Salida", description: "Última mañana en la playa y traslado al aeropuerto." },
    ],
    included: ["Traslados", "Alojamiento", "Desayuno", "Excursiones seleccionadas"],
    excluded: ["Vuelos", "Almuerzos y cenas", "Seguro de viaje", "Gastos personales"],
    bestTime: "Junio a marzo",
    groupSize: "2 a 8 personas",
  },
  "saadani-national-park": {
    title: "Parque nacional de Saadani",
    location: "Tanzania",
    duration: "3 días",
    price: "Desde 1.600 $",
    description: "Donde la sabana se encuentra con la playa: Saadani combina paisajes costeros y observación de fauna para una extensión única en Tanzania.",
    highlights: ["Paisajes de safari costeros", "Safaris con vista al mar", "Salidas en barco y fauna fluvial", "Ambiente tranquilo y poco concurrido", "Ideal para una extensión corta"],
    itinerary: [
      { day: 1, title: "Llegada y safari por la tarde", description: "Llegada y safari a través de llanuras costeras y corredores fluviales." },
      { day: 2, title: "Safari y opción fluvial", description: "Safari matutino y excursión fluvial opcional según la temporada." },
      { day: 3, title: "Última mañana y salida", description: "Breve actividad matutina y traslado de salida." },
    ],
    included: ["Alojamiento", "Comidas", "Tarifas de parque", "Safaris", "Servicios de guía"],
    excluded: ["Vuelos", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 8 personas",
  },
  "mahale-mountains-national-park": {
    title: "Parque nacional de las montañas Mahale",
    location: "Tanzania",
    duration: "5 días",
    price: "Desde 3.400 $",
    description: "Vuele hacia el lago Tanganica para un trekking de chimpancés en Mahale, una de las experiencias más ricas y remotas de Tanzania.",
    highlights: ["Trekking de chimpancés", "Paisajes del lago Tanganica", "Senderismo en montaña forestal", "Aventura aérea en una zona remota", "Perfecto para amantes de la naturaleza"],
    itinerary: [
      { day: 1, title: "Llegada y orilla del lago", description: "Llegada en avión o barco, instalación y descubrimiento de las orillas del lago." },
      { day: 2, title: "Trek de chimpancés", description: "Caminata matutina en busca de chimpancés con rastreadores expertos." },
      { day: 3, title: "Segundo trek o senderismo", description: "Elija un nuevo trek o una caminata más larga según las condiciones." },
      { day: 4, title: "Tiempo en el lago", description: "Relajación con baño, kayak o excursión suave en barco." },
      { day: 5, title: "Salida", description: "Traslado a la siguiente etapa de su viaje." },
    ],
    included: ["Tarifas de parque", "Alojamiento", "Comidas", "Trekking de chimpancés", "Traslados locales"],
    excluded: ["Vuelos", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 6 personas",
  },
  "lake-natron": {
    title: "Lago Natron",
    location: "Tanzania",
    duration: "2 días",
    price: "Desde 750 $",
    description: "Descubra uno de los paisajes más espectaculares del este de África: aguas alcalinas llenas de flamencos, entorno volcánico y puerta de entrada al Ol Doinyo Lengai.",
    highlights: ["Colonias de flamencos menores", "Paisajes volcánicos", "Cascadas y cultura masái", "Circuito norte fuera de lo común", "Excelentes oportunidades fotográficas"],
    itinerary: [
      { day: 1, title: "Arusha - lago Natron", description: "Ruta panorámica a través de aldeas masái con paradas en cascadas y miradores." },
      { day: 2, title: "Orilla del lago y regreso", description: "Mañana a orillas del lago para flamencos y paisajes y regreso a Arusha." },
    ],
    included: ["Transporte", "Alojamiento", "Comidas", "Servicios de guía", "Tarifas de conservación"],
    excluded: ["Vuelos", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Junio a octubre",
    groupSize: "2 a 6 personas",
  },
  "arusha-national-park": {
    title: "Parque nacional de Arusha",
    location: "Tanzania",
    duration: "1 día",
    price: "Desde 350 $",
    description: "Una joya compacta al pie del monte Meru: jirafas, búfalos, colobos y lagos de cráter a pocos minutos de Arusha.",
    highlights: ["Vista del monte Meru", "Miradores del cráter de Ngurdoto", "Avifauna de los lagos Momella", "Safaris a pie disponibles", "Ideal para aclimatarse antes del Kilimanjaro"],
    itinerary: [
      { day: 1, title: "Safari de un día", description: "Recogida por la mañana, safari entre bosque y lagos, almuerzo de picnic, observación de fauna y regreso a Arusha." },
    ],
    included: ["Tarifas de parque", "Vehículo privado 4x4", "Guía profesional", "Almuerzo de picnic", "Traslados desde el hotel"],
    excluded: ["Vuelos", "Seguro de viaje", "Gastos personales", "Propinas"],
    bestTime: "Todo el año",
    groupSize: "2 a 6 personas",
  },
}

export const esTrekOverlays: Record<string, Partial<Trek>> = {
  "kilimanjaro-marangu-route": {
    title: "Ruta Marangu",
    headline: "Ruta Marangu de 5 días - Ascenso al Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "5 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "La única ruta del Kilimanjaro con alojamiento en refugio. Ideal para principiantes que buscan comodidad y un itinerario más corto hacia la cumbre.",
    overview: "La ruta Marangu es la forma más establecida y cómoda de ascender el Kilimanjaro. Es la única ruta con alojamiento en refugio compartido, perfecta para senderistas que prefieren evitar el campamento. El sendero atraviesa bosque tropical, landas, desierto alpino y alcanza Uhuru Peak (5.895 m), el punto más alto de África.",
    priceFrom: "2.100 $ por persona",
    highlights: ["Única ruta con alojamiento en refugio", "Ideal para principiantes", "Sendero progresivo y bien mantenido", "Ascenso clásico vía Gilman's Point", "Refugios cómodos en cada campamento"],
    whyChoose: ["Alojamiento en refugio en lugar de tienda", "Duración más corta y logística sencilla", "Adecuada para una condición física moderada", "Buen índice de éxito con un ritmo adaptado"],
    itinerary: [
      { day: "Día 1", title: "Marangu Gate - Mandara Hut", description: "Inicio del ascenso a través del exuberante bosque tropical hasta Mandara Hut (2.700 m)." },
      { day: "Día 2", title: "Mandara Hut - Horombo Hut", description: "Ascenso hacia las landas con vistas espectaculares de Mawenzi y Kibo hasta Horombo Hut (3.720 m)." },
      { day: "Día 3", title: "Horombo Hut - Kibo Hut", description: "Travesía del desierto alpino entre Mawenzi y Kibo y llegada a Kibo Hut (4.700 m)." },
      { day: "Día 4", title: "Cumbre y descenso a Horombo", description: "Ascenso nocturno hacia Uhuru Peak al amanecer y descenso a Horombo Hut." },
      { day: "Día 5", title: "Horombo Hut - Marangu Gate", description: "Descenso final por el bosque y entrega del certificado." },
    ],
  },
  "kilimanjaro-machame-route": {
    title: "Ruta Machame",
    headline: "Ruta Machame de 7 días - Ascenso al Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "7 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "La ruta más popular del Kilimanjaro, que ofrece paisajes espectaculares y una excelente aclimatación gracias al principio de 'subir alto, dormir bajo'.",
    overview: "Apodada la ruta del Whisky, Machame es el sendero más popular del Kilimanjaro. Su excelente perfil de aclimatación la convierte en una de las rutas con mejores índices de éxito en la cumbre.",
    priceFrom: "2.200 $ por persona",
    highlights: ["Ruta más popular del Kilimanjaro", "Excelente perfil de aclimatación", "Paisajes variados desde el bosque hasta los glaciares", "Ascenso emblemático del Barranco Wall", "Alto índice de éxito"],
    whyChoose: ["Mejor equilibrio entre desafío y recompensa", "Ideal para trekkers aventureros", "Paisajes variados y fotogénicos", "Sólidas estadísticas de éxito en la cumbre"],
    itinerary: [
      { day: "Día 1", title: "Machame Gate - Machame Camp", description: "Caminata a través de un bosque denso hasta Machame Camp (3.000 m)." },
      { day: "Día 2", title: "Machame Camp - Shira 2", description: "Ascenso empinado hacia las landas y travesía de la meseta de Shira hasta 3.850 m." },
      { day: "Día 3", title: "Shira 2 - Lava Tower - Barranco", description: "Día de aclimatación vía Lava Tower antes de descender al valle de Barranco." },
      { day: "Día 4", title: "Barranco - Karanga", description: "Ascenso del Barranco Wall y travesía hacia Karanga Camp." },
      { day: "Día 5", title: "Karanga - Barafu", description: "Ascenso a Barafu Camp, base de partida para la noche de cumbre." },
      { day: "Día 6", title: "Cumbre y Mweka Camp", description: "Ascenso nocturno hacia Uhuru Peak y descenso hasta Mweka Camp." },
      { day: "Día 7", title: "Mweka Camp - Mweka Gate", description: "Descenso final por el bosque y regreso a Arusha o Moshi." },
    ],
  },
  "kilimanjaro-lemosho-route": {
    title: "Ruta Lemosho",
    headline: "Ruta Lemosho de 8 días - Ascenso panorámico al Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "8 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "Una de las rutas más bellas del Kilimanjaro, con menos afluencia, un inicio salvaje y uno de los mejores índices de éxito.",
    overview: "La ruta Lemosho suele considerarse la forma más bella de ascender el Kilimanjaro. Comienza en las laderas occidentales, atraviesa la vasta meseta de Shira y ofrece una aclimatación progresiva excepcional.",
    priceFrom: "2.380 $ por persona",
    highlights: ["Ruta más panorámica", "Baja afluencia", "Excelente programa de aclimatación", "Muy alto índice de éxito", "Aproximación salvaje por el oeste"],
    whyChoose: ["Experiencia premium", "Ideal para escaladores serios", "Menos concurrida que Machame", "Aclimatación más larga para mayor seguridad"],
    itinerary: [
      { day: "Día 1", title: "Londorossi Gate - Mti Mkubwa", description: "Inicio en bosque tropical por la ladera oeste hasta Mti Mkubwa (2.750 m)." },
      { day: "Día 2", title: "Mti Mkubwa - Shira 1", description: "Salida del bosque hacia las landas hasta Shira 1 Camp (3.500 m)." },
      { day: "Día 3", title: "Shira 1 - Shira 2", description: "Caminata suave por la meseta de Shira con vistas del monte Meru y Kibo." },
      { day: "Día 4", title: "Shira 2 - Lava Tower - Barranco", description: "Ascenso hacia Lava Tower para aclimatación y descenso a Barranco." },
      { day: "Día 5", title: "Barranco - Karanga", description: "Paso del Barranco Wall y travesía hacia Karanga Camp." },
      { day: "Día 6", title: "Karanga - Barafu", description: "Llegada a Barafu Camp y preparación para la noche de cumbre." },
      { day: "Día 7", title: "Cumbre y Mweka Camp", description: "Ascenso nocturno hacia Uhuru Peak vía Stella Point y descenso a Mweka." },
      { day: "Día 8", title: "Mweka Camp - Mweka Gate", description: "Descenso final por el bosque y celebración de su logro." },
    ],
  },
  "kilimanjaro-rongai-route": {
    title: "Ruta Rongai",
    headline: "Ruta Rongai de 6 días - Aproximación norte al Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "6 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "La única ruta que aborda el Kilimanjaro por el norte, cerca de Kenia. Tranquila, seca e ideal para una experiencia más salvaje.",
    overview: "Rongai es la única ruta que se acerca al Kilimanjaro desde el norte, cerca de la frontera con Kenia. Más seca y menos concurrida, es muy adecuada durante las temporadas húmedas.",
    priceFrom: "2.150 $ por persona",
    highlights: ["Ruta menos concurrida", "Condiciones más secas todo el año", "Ascenso progresivo", "Magníficos panoramas del lado norte", "Posibilidades de observar fauna en las laderas bajas"],
    whyChoose: ["Ideal durante la temporada de lluvias", "Menos tráfico que las rutas del sur", "Pendiente regular", "Ambiente más salvaje"],
    itinerary: [
      { day: "Día 1", title: "Rongai Gate - Simba Camp", description: "Inicio a través de las laderas boscosas del norte hasta Simba Camp (2.650 m)." },
      { day: "Día 2", title: "Simba Camp - Kikelewa Camp", description: "Ascenso por las landas con vistas de Mawenzi y las llanuras del norte." },
      { day: "Día 3", title: "Kikelewa - Mawenzi Tarn", description: "Ascenso por un espectacular valle alpino hasta Mawenzi Tarn (4.330 m)." },
      { day: "Día 4", title: "Mawenzi Tarn - Kibo Hut", description: "Travesía del desierto alpino hasta Kibo Hut (4.700 m)." },
      { day: "Día 5", title: "Cumbre y Horombo Hut", description: "Ascenso nocturno hacia Uhuru Peak vía Gilman's Point y descenso a Horombo." },
      { day: "Día 6", title: "Horombo Hut - Marangu Gate", description: "Descenso final por el bosque y entrega del certificado." },
    ],
  },
  "umbwe-route": {
    title: "Ruta Umbwe",
    headline: "Ruta Umbwe de 6 días - Ascenso empinado al Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "6 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "La ruta más empinada y directa del Kilimanjaro. Recomendada para trekkers experimentados en busca de un desafío.",
    overview: "La ruta Umbwe es el itinerario más abrupto del Kilimanjaro. Asciende rápidamente a través del bosque y las crestas antes de unirse al circuito sur en Barranco.",
    priceFrom: "2.150 $ por persona",
    highlights: ["Ascenso empinado y directo", "Menos concurrida", "Acceso rápido al valle de Barranco", "Progresión por crestas", "Experiencia muy deportiva"],
    whyChoose: ["Camino más directo hacia la cumbre", "Ideal para senderistas experimentados", "Ambiente más salvaje", "Crestas espectaculares"],
    itinerary: [
      { day: "Día 1", title: "Umbwe Gate - Umbwe Cave Camp", description: "Ascenso empinado por bosque denso hasta Umbwe Cave (2.940 m)." },
      { day: "Día 2", title: "Umbwe Cave - Barranco Camp", description: "Continuación del ascenso por la cresta con vistas impresionantes y llegada a Barranco." },
      { day: "Día 3", title: "Barranco - Karanga", description: "Ascenso del Barranco Wall y travesía hacia Karanga Camp." },
      { day: "Día 4", title: "Karanga - Barafu", description: "Ascenso a Barafu Camp y descanso antes del esfuerzo final." },
      { day: "Día 5", title: "Cumbre y Mweka Camp", description: "Ascenso hacia Uhuru Peak y descenso a Mweka Camp." },
      { day: "Día 6", title: "Mweka Camp - Mweka Gate", description: "Descenso final por el bosque y regreso al hotel." },
    ],
  },
  "shira-route": {
    title: "Ruta Shira",
    headline: "Ruta Shira de 7 días - Trek occidental del Kilimanjaro",
    location: "Parque nacional del Kilimanjaro, Tanzania",
    duration: "7 días",
    elevation: "5.895 m (Uhuru Peak)",
    bestTime: "Junio - octubre y enero - marzo",
    permits: "Se requieren permisos del parque nacional del Kilimanjaro",
    description: "Una aproximación panorámica por el oeste que comienza en altitud en la meseta de Shira. Paisajes muy bellos y buena aclimatación.",
    overview: "La ruta Shira comienza a gran altitud en la ladera occidental del Kilimanjaro, ofreciendo acceso inmediato a la meseta de Shira y panoramas excepcionales antes de unirse a los itinerarios Machame y Lemosho.",
    priceFrom: "2.300 $ por persona",
    highlights: ["Travesía panorámica de la meseta de Shira", "Inicio occidental más remoto", "Paisajes abiertos espectaculares", "Buen índice de éxito", "Menos afluencia al inicio"],
    whyChoose: ["Inmersión rápida en gran altitud", "Buen potencial de aclimatación", "Magníficos paisajes de meseta", "Aproximación occidental más tranquila"],
    itinerary: [
      { day: "Día 1", title: "Shira Gate - Shira 1", description: "Inicio en altitud a través de las landas hasta Shira 1 Camp." },
      { day: "Día 2", title: "Shira 1 - Shira 2", description: "Caminata suave por la meseta con vistas de Kibo y el monte Meru." },
      { day: "Día 3", title: "Shira 2 - Barranco vía Lava Tower", description: "Ascenso hacia Lava Tower y descenso a Barranco Camp." },
      { day: "Día 4", title: "Barranco - Karanga", description: "Ascenso del Barranco Wall y continuación hacia Karanga." },
      { day: "Día 5", title: "Karanga - Barafu", description: "Ascenso a Barafu Camp y preparación para el ascenso nocturno." },
      { day: "Día 6", title: "Cumbre y Mweka Camp", description: "Ascenso hacia Uhuru Peak vía Stella Point y descenso a Mweka." },
      { day: "Día 7", title: "Mweka Camp - Mweka Gate", description: "Descenso final a través del bosque tropical." },
    ],
  },
  "mount-meru-trek": {
    title: "Trek del monte Meru",
    headline: "Trek del monte Meru de 4 días - Parque nacional de Arusha",
    location: "Parque nacional de Arusha, Tanzania",
    duration: "4 días",
    elevation: "4.566 m (Socialist Peak)",
    bestTime: "Junio - octubre y enero - febrero",
    permits: "Se requieren tarifas de parque y guardaparque armado",
    description: "La segunda cumbre más alta de Tanzania y un excelente trek de aclimatación antes del Kilimanjaro.",
    overview: "El trek del monte Meru es una magnífica aventura de 4 días en el parque nacional de Arusha. Combina observación de fauna en las laderas bajas y un espectacular ascenso del borde del cráter hasta Socialist Peak (4.566 m).",
    priceFrom: "1.000 $ por persona",
    highlights: ["Encuentros con fauna en las laderas bajas", "Vistas espectaculares del cráter", "Perfecta aclimatación para el Kilimanjaro", "Menos concurrido", "Cumbre al amanecer"],
    whyChoose: ["Excelente aclimatación antes del Kilimanjaro", "Fauna abundante, incluidos búfalos y jirafas", "Paisajes volcánicos impresionantes", "Más corto y asequible que el Kilimanjaro"],
    itinerary: [
      { day: "Día 1", title: "Momella Gate - Miriakamba Hut", description: "Ascenso a través de bosque y praderas con avistamientos de fauna hasta Miriakamba Hut (2.514 m)." },
      { day: "Día 2", title: "Miriakamba Hut - Saddle Hut", description: "Ascenso más exigente con vistas panorámicas del cráter y el Kilimanjaro." },
      { day: "Día 3", title: "Cumbre y regreso a Miriakamba", description: "Ascenso nocturno hacia Socialist Peak y descenso a Miriakamba Hut." },
      { day: "Día 4", title: "Miriakamba Hut - Momella Gate", description: "Descenso final a través del parque nacional de Arusha y regreso a Arusha." },
    ],
  },
  "ol-doinyo-lengai-night-hike": {
    title: "Ascenso nocturno del Ol Doinyo Lengai",
    headline: "Ascenso del volcán activo Ol Doinyo Lengai",
    location: "Lago Natron, Tanzania",
    duration: "1 noche",
    elevation: "2.962 m",
    bestTime: "Junio - octubre",
    permits: "Se requiere guía local",
    description: "Ascienda de noche el único volcán activo de Tanzania para admirar vistas espectaculares del valle del Rift al amanecer.",
    overview: "El Ol Doinyo Lengai es el único volcán activo de Tanzania y una montaña sagrada para los masái. Este exigente ascenso nocturno conduce a una cumbre con una vista impresionante del valle del Rift, el lago Natron y el Kilimanjaro a lo lejos.",
    priceFrom: "350 $ por persona",
    highlights: ["Ascenso de un volcán activo", "Cumbre al amanecer", "Región cultural masái", "Aventura exigente", "Entorno salvaje y aislado"],
  },
  "packing-list": {
    title: "Lista de equipo para el Kilimanjaro",
    headline: "Lista esencial para el Kilimanjaro",
    location: "Monte Kilimanjaro, Tanzania",
    duration: "Guía de preparación",
    elevation: "Hasta 5.895 m",
    bestTime: "Todo el año",
    permits: "No se requieren permisos para esta guía",
    description: "Lista completa para ascender el Kilimanjaro de forma segura y cómoda.",
    overview: "Preparar el Kilimanjaro requiere ropa adecuada, un buen sistema de capas, equipo de dormir eficaz y accesorios esenciales. El material adecuado mejora notablemente sus posibilidades de alcanzar la cumbre en buenas condiciones.",
    highlights: ["Sistema de ropa multicapa", "Saco de dormir de gran altitud", "Equipo impermeable", "Buenas botas de trekking", "Linterna frontal y bastones de trekking"],
  },
  "altitude-acclimatization": {
    title: "Altitud y aclimatación",
    headline: "Comprender la altitud en el Kilimanjaro",
    location: "Monte Kilimanjaro",
    duration: "Guía de preparación",
    elevation: "5.895 m",
    bestTime: "Todo el año",
    permits: "No se requieren permisos",
    description: "Comprenda cómo una buena aclimatación aumenta sus posibilidades de alcanzar Uhuru Peak con seguridad.",
    overview: "El mal agudo de montaña es el principal desafío en el Kilimanjaro. Elegir una ruta más larga, mantenerse bien hidratado y avanzar a un ritmo progresivo mejora considerablemente las posibilidades de éxito.",
    highlights: ["Principio de 'subir alto, dormir bajo'", "Importancia de la hidratación", "Estrategia de ascenso progresivo", "Vigilancia de los síntomas del MAM"],
  },
  "best-time-to-climb": {
    title: "Mejor época para ascender el Kilimanjaro",
    headline: "Guía estacional para el ascenso al Kilimanjaro",
    location: "Monte Kilimanjaro",
    duration: "Guía de preparación",
    elevation: "5.895 m",
    bestTime: "Enero-marzo y junio-octubre",
    permits: "No se requieren permisos",
    description: "Análisis estacional de las condiciones meteorológicas y de cumbre en el Kilimanjaro.",
    overview: "El Kilimanjaro puede ascenderse todo el año, pero las temporadas secas suelen ofrecer mejor visibilidad y condiciones más seguras para la cumbre.",
    highlights: ["Ventajas de la temporada seca", "Consideraciones para la temporada de lluvias", "Temperaturas esperadas", "Nivel de afluencia según los meses"],
  },
  "climbing-faqs": {
    title: "Preguntas frecuentes sobre el ascenso al Kilimanjaro",
    headline: "Preguntas frecuentes sobre el Kilimanjaro",
    location: "Monte Kilimanjaro",
    duration: "Guía informativa",
    elevation: "5.895 m",
    bestTime: "Todo el año",
    permits: "No se requieren permisos",
    description: "Las preguntas más frecuentes sobre el ascenso al Kilimanjaro, explicadas por nuestros expertos en montaña.",
    overview: "Encuentre respuestas claras sobre la condición física necesaria, el entrenamiento, la seguridad, el mal de altura, los índices de éxito y la preparación de su expedición.",
    highlights: ["¿Necesito experiencia previa?", "¿Qué nivel de forma física se requiere?", "¿Cuál es el índice de éxito en la cumbre?", "¿Qué frío hace?"],
  },
  "udzungwa-mountains-waterfalls-hike": {
    title: "Senderismo a cascadas en las montañas Udzungwa",
    headline: "Trek por bosque tropical y cascadas de Udzungwa",
    location: "Parque nacional de las montañas Udzungwa",
    duration: "1 a 3 días",
    elevation: "Hasta 2.576 m",
    bestTime: "Junio - octubre",
    permits: "Se requieren tarifas de parque",
    description: "Senderismo por bosque tropical con cascadas espectaculares y fauna endémica.",
    highlights: ["Cascadas de Sanje", "Biodiversidad del bosque", "Clima agradable", "Fauna endémica", "Oportunidades fotográficas"],
  },
  "usambara-mountains-cultural-walks": {
    title: "Caminatas culturales en las montañas Usambara",
    headline: "Senderismo por aldeas y cultura",
    location: "Lushoto, Tanzania",
    duration: "1 a 4 días",
    elevation: "1.200 m - 2.300 m",
    bestTime: "Junio - octubre",
    permits: "Se recomienda guía local",
    description: "Senderismo tranquilo por las mesetas altas a través de aldeas y miradores panorámicos.",
    highlights: ["Caminatas por aldeas", "Temperaturas frescas", "Encuentros culturales", "Hermosos panoramas", "Senderismo apto para familias"],
  },
  "ngorongoro-highlands-empakaai-crater-trek": {
    title: "Trek del cráter de Empakaai",
    headline: "Safari a pie en las tierras altas del Ngorongoro",
    location: "Área de conservación del Ngorongoro",
    duration: "1 a 2 días",
    elevation: "3.200 m",
    bestTime: "Junio - octubre, enero - marzo",
    permits: "Se requieren tarifas de conservación",
    description: "Senderismo guiado por el borde del cráter en las tierras altas del Ngorongoro con vistas del lago de flamencos.",
    highlights: ["Paisajes volcánicos", "Vista del lago de flamencos", "Entornos masái", "Senderismo de altitud", "Ideal como extensión de safari"],
  },
}

export const esLocalizedOverlays = {
  safaris: esSafariOverlays,
  dayTrips: esDayTripOverlays,
  zanzibar: esZanzibarOverlays,
  adventures: esAdventureOverlays,
  destinations: esDestinationOverlays,
  treks: esTrekOverlays,
}
