import type { Adventure } from "@/lib/adventures-data"
import type { DayTrip } from "@/lib/day-trips-data"
import type { Destination } from "@/lib/destinations-data"
import type { SafariPackage } from "@/lib/safaris-data"
import type { Trek } from "@/lib/treks-data"
import type { ZanzibarExperience } from "@/lib/zanzibar-experiences"

export const frSafariOverlays: Record<string, Partial<SafariPackage>> = {
  "big-five": {
    title: "Safari Big Five de 3 jours",
    region: "Nord de la Tanzanie",
    duration: "3 jours",
    price: "A partir de 1 200 $",
    description:
      "Safari court idéal pour une première découverte, avec l'objectif d'observer les Big Five à Tarangire et au lac Manyara.",
    highlights: [
      "Faune des Big Five",
      "Éléphants de Tarangire",
      "Paysages du lac Manyara",
      "Véhicule privé 4x4",
      "Excellent rapport qualité-prix",
    ],
    itinerary: [
      { day: 1, title: "Arusha - Tarangire", description: "Transfert vers le parc national de Tarangire avec safari l'après-midi." },
      { day: 2, title: "Journée complète à Tarangire", description: "Safari d'une journée entière centré sur les éléphants et les lions." },
      { day: 3, title: "Lac Manyara et retour", description: "Matinée au lac Manyara puis retour à Arusha." },
    ],
    includes: ["Frais de parc", "Hébergement", "Repas", "Guide privé", "Véhicule 4x4"],
  },
  "big-five-short": {
    title: "Escapade Big Five de 3 jours",
    region: "Nord de la Tanzanie",
    duration: "3 jours",
    price: "A partir de 1 200 $",
    description:
      "Safari intense de 3 jours axé sur les Big Five dans les parcs de Tarangire et du lac Manyara.",
    highlights: [
      "Itinéraire compact",
      "Focus Big Five",
      "Parfait pour un court séjour",
      "Véhicule privé",
      "Guide expert",
    ],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Transfert puis safari dans le parc national de Tarangire." },
      { day: 2, title: "Journée complète à Tarangire", description: "Observation prolongée de la faune à Tarangire." },
      { day: 3, title: "Lac Manyara", description: "Safari matinal puis retour à Arusha." },
    ],
    includes: ["Frais de parc", "Hébergement", "Repas", "Guide", "Transport"],
  },
  "wonders-of-tanzania": {
    title: "Les merveilles de la Tanzanie en 6 jours",
    region: "Nord de la Tanzanie",
    duration: "6 jours",
    price: "A partir de 2 800 $",
    description:
      "Safari complet couvrant Tarangire, le Serengeti et le cratère du Ngorongoro.",
    highlights: [
      "Plaines du Serengeti",
      "Cratère du Ngorongoro",
      "Éléphants de Tarangire",
      "Lodges de catégorie intermédiaire",
      "Rythme équilibré",
    ],
    itinerary: [
      { day: 1, title: "Tarangire", description: "Départ d'Arusha vers le parc national de Tarangire." },
      { day: "2-3", title: "Serengeti", description: "Safaris dans le parc national du Serengeti." },
      { day: "4-5", title: "Ngorongoro", description: "Descente dans le cratère et observation de la faune." },
      { day: 6, title: "Retour", description: "Retour à Arusha." },
    ],
    includes: ["Tous les frais de parc", "Hébergement", "Pension complète", "Guide privé", "Land Cruiser 4x4"],
  },
  "bush-and-beach": {
    title: "Safari de luxe bush et plage en 8 jours",
    region: "Nord de la Tanzanie et Zanzibar",
    duration: "8 jours",
    price: "A partir de 5 400 $",
    description:
      "Combinez un safari de luxe dans le Serengeti et au Ngorongoro avec un séjour détente sur les plages de Zanzibar.",
    highlights: [
      "Safari sur le circuit nord",
      "Extension balnéaire à Zanzibar",
      "Visite de Stone Town",
      "Lodges de luxe",
      "Transferts privés",
    ],
    itinerary: [
      { day: "1-5", title: "Circuit nord", description: "Safari à Tarangire, au Serengeti et au Ngorongoro." },
      { day: 6, title: "Vol pour Zanzibar", description: "Transfert vers votre resort balnéaire à Zanzibar." },
      { day: 7, title: "Plage et culture", description: "Options de visite à Stone Town et de tour des épices." },
      { day: 8, title: "Départ", description: "Matinée à la plage puis transfert à l'aéroport." },
    ],
    includes: ["Logistique safari", "Vol domestique vers Zanzibar", "Hôtel de plage", "Excursions sélectionnées", "Guide privé"],
  },
  "great-migration-safari": {
    title: "Safari Grande Migration au Serengeti",
    region: "Nord de la Tanzanie",
    duration: "8 jours",
    price: "A partir de 4 600 $",
    description:
      "Assistez à l'un des plus grands spectacles animaliers du monde : la Grande Migration des gnous.",
    highlights: [
      "Traversées de la rivière Mara",
      "Observations des Big Five",
      "Véhicule privé 4x4",
      "Camps de luxe sous tente",
    ],
    itinerary: [
      { day: 1, title: "Arrivée à Arusha", description: "Transfert vers votre lodge pour un briefing." },
      { day: "2-3", title: "Serengeti central", description: "Safaris au cœur du territoire des grands félins." },
      { day: "4-6", title: "Serengeti nord", description: "Suivi des troupeaux près de la rivière Mara." },
      { day: 7, title: "Cratère du Ngorongoro", description: "Descente dans ce jardin d'Éden africain." },
      { day: 8, title: "Départ", description: "Retour à Arusha pour votre vol retour." },
    ],
    includes: ["Tous les frais de parc", "Guide privé", "Pension complète", "Land Cruiser 4x4"],
  },
  "private-tours": {
    title: "Safaris privés sur mesure",
    region: "Toute la Tanzanie",
    duration: "Sur mesure",
    price: "Tarification sur demande",
    description:
      "Des itinéraires exclusifs conçus pour les couples, les familles ou les petits groupes recherchant une flexibilité totale.",
    highlights: [
      "Guide privé dédié",
      "Programme quotidien personnalisé",
      "Lodges soigneusement sélectionnés",
      "4x4 privé",
    ],
    itinerary: [
      { day: "Note", title: "Journées personnalisables", description: "Nous construisons l'itinéraire autour de vos centres d'intérêt et de votre rythme." },
    ],
    includes: ["Transport privé", "Guide naturaliste expert", "Planification personnalisée"],
  },
  "safari-vehicles": {
    title: "Nos Land Cruisers 4x4 pour safari",
    region: "Logistique",
    duration: "Spécifications techniques",
    price: "Inclus dans les circuits",
    description:
      "Notre flotte se compose de Land Cruisers 4x4 spécialement aménagés pour les terrains exigeants de Tanzanie.",
    highlights: [
      "Toit relevable avec vue à 360°",
      "Points de recharge à bord",
      "Réfrigérateur pour boissons fraîches",
      "Radio longue portée",
    ],
    itinerary: [
      { day: "Confort", title: "Espace et visibilité", description: "Châssis allongés pour plus d'espace aux jambes et grandes fenêtres panoramiques." },
      { day: "Sécurité", title: "Entretien", description: "Chaque véhicule est révisé après chaque safari." },
    ],
    includes: ["Place côté fenêtre garantie", "Snorkel pour passages d'eau", "Guides de terrain et jumelles"],
  },
  "packing-list": {
    title: "Les essentiels de la valise safari",
    region: "Préparation",
    duration: "Checklist",
    price: "Guide expert",
    description:
      "Assurez-vous d'avoir tout le nécessaire pour une aventure confortable et sûre en pleine brousse.",
    highlights: [
      "Vêtements aux couleurs neutres",
      "Protection solaire",
      "Jumelles de qualité",
      "Traitement antipaludique",
    ],
    itinerary: [
      { day: "Vêtements", title: "Que porter", description: "Les couches sont essentielles. Matins frais, après-midis chauds. Évitez le bleu et le noir à cause des mouches tsé-tsé." },
      { day: "Équipement", title: "Technologie essentielle", description: "Appareil photo, batteries de rechange et batteries externes sont indispensables dans les zones reculées." },
    ],
    includes: ["Checklist standard", "Exigences de visa", "Conseils santé"],
  },
  "honeymoon-safari": {
    title: "Safaris de lune de miel romantiques",
    region: "Tanzanie romantique",
    duration: "7 à 12 jours",
    price: "A partir de 5 200 $",
    description:
      "Alliez le frisson de la vie sauvage à un luxe intime dans les cadres les plus romantiques d'Afrique.",
    highlights: [
      "Dîners privés dans le bush",
      "Nuits en star-bed",
      "Extensions à Zanzibar",
      "Safari en montgolfière",
    ],
    itinerary: [
      { day: "Ambiance", title: "Luxe intimiste", description: "Nous sélectionnons de petits camps isolés qui privilégient l'intimité et le romantisme." },
    ],
    includes: ["Massage en couple", "Apéritifs au champagne au coucher du soleil", "Transferts privés"],
  },
}

export const frDayTripOverlays: Record<string, Partial<DayTrip>> = {
  "chemka-hot-springs": {
    title: "Excursion à Chemka Hot Springs",
    shortTitle: "Chemka Hot Springs",
    description:
      "Évadez-vous vers les eaux cristallines de Chemka Hot Springs, un paradis naturel niché au pied du Kilimandjaro. Profitez d'une baignade rafraîchissante, détendez-vous sur les rives sablonneuses et découvrez des eaux chaudes riches en minéraux.",
    highlight: "Baignade dans des sources chaudes naturelles cristallines",
    duration: "Journée complète",
    location: "Kikuletwa, Kilimandjaro",
    highlights: [
      "Baignade dans des sources chaudes naturelles limpides",
      "Détente sur des plages de sable",
      "Déjeuner traditionnel au bord de l'eau",
      "Route panoramique à travers les plantations de café",
      "Superbes opportunités photo",
    ],
    included: ["Frais d'entrée", "Guide professionnel", "Transport privé", "Déjeuner local", "Eau potable"],
    notIncluded: ["Dépenses personnelles", "Pourboires", "Assurance voyage"],
    itinerary: [
      { time: "07:00", activity: "Prise en charge à votre hôtel à Arusha" },
      { time: "08:30", activity: "Route panoramique vers Chemka via les plantations de café" },
      { time: "09:30", activity: "Arrivée à Chemka Hot Springs et changement" },
      { time: "10:00", activity: "Baignade et détente dans les bassins naturels" },
      { time: "12:30", activity: "Déjeuner servi au bord du bassin" },
      { time: "14:00", activity: "Temps libre pour nager et explorer" },
      { time: "15:30", activity: "Départ vers Arusha" },
      { time: "17:00", activity: "Retour à votre hôtel" },
    ],
  },
  "lake-duluti": {
    title: "Excursion au lac Duluti",
    shortTitle: "Lac Duluti",
    description:
      "Découvrez la beauté paisible du lac Duluti, superbe lac de cratère situé juste à l'extérieur d'Arusha. Promenade guidée en forêt, observation d'oiseaux et sortie en canoë sur des eaux calmes.",
    highlight: "Balade en canoë sur un lac de cratère pittoresque",
    duration: "Demi-journée / journée complète",
    location: "Arusha",
    highlights: [
      "Promenade guidée en forêt autour du lac",
      "Canoë sur le lac de cratère",
      "Observation de plus de 200 espèces d'oiseaux",
      "Pique-nique au bord du lac",
      "Rencontre culturelle avec les communautés locales",
    ],
    included: ["Frais d'entrée", "Guide professionnel", "Transport privé", "Location de canoë", "Déjeuner (journée complète)", "Eau potable"],
    notIncluded: ["Dépenses personnelles", "Pourboires", "Assurance voyage"],
    itinerary: [
      { time: "08:00", activity: "Prise en charge à votre hôtel à Arusha" },
      { time: "09:00", activity: "Arrivée au lac Duluti et rencontre avec votre guide" },
      { time: "09:30", activity: "Promenade guidée autour du cratère" },
      { time: "11:00", activity: "Sortie en canoë sur le lac Duluti" },
      { time: "12:30", activity: "Pique-nique au bord du lac" },
      { time: "14:00", activity: "Observation des oiseaux et photographie" },
      { time: "15:30", activity: "Départ vers Arusha" },
      { time: "16:30", activity: "Retour à votre hôtel" },
    ],
  },
  "arusha-town-tour": {
    title: "Visite de la ville d'Arusha",
    shortTitle: "Visite d'Arusha",
    description:
      "Découvrez Arusha avec un guide local : sites du patrimoine, marchés animés et vie quotidienne vibrante de la capitale safari de Tanzanie.",
    highlight: "Balade culturelle guidée dans Arusha",
    duration: "Demi-journée",
    location: "Arusha",
    highlights: [
      "Sites emblématiques du centre d'Arusha",
      "Histoire et culture locales",
      "Visites de marchés",
      "Arrêts artisanat et souvenirs",
      "Rythme privé et flexible",
    ],
    included: ["Guide professionnel", "Transport privé", "Eau en bouteille"],
    notIncluded: ["Repas", "Achats personnels", "Pourboires"],
    itinerary: [
      { time: "09:00", activity: "Prise en charge à l'hôtel à Arusha" },
      { time: "09:30", activity: "Visite à pied du centre d'Arusha" },
      { time: "11:00", activity: "Découverte de sites culturels et de marchés" },
      { time: "12:30", activity: "Suggestion de déjeuner en option" },
      { time: "13:30", activity: "Retour à l'hôtel" },
    ],
  },
  "curios-gift-shops": {
    title: "Tour des boutiques d'artisanat et cadeaux",
    shortTitle: "Artisanat et cadeaux",
    description:
      "Parcourez les meilleures boutiques d'Arusha et les ateliers d'artisans pour découvrir perles masaï, peintures Tinga Tinga, sculptures et souvenirs faits main.",
    highlight: "Artisanat et cadeaux authentiques de Tanzanie",
    duration: "Demi-journée",
    location: "Arusha",
    highlights: [
      "Ateliers d'artisans",
      "Boutiques équitables",
      "Perles masaï",
      "Art Tinga Tinga",
      "Conseils d'expédition disponibles",
    ],
    included: ["Guide", "Transport entre les boutiques", "Eau en bouteille"],
    notIncluded: ["Achats", "Frais d'expédition", "Pourboires"],
    itinerary: [
      { time: "09:00", activity: "Prise en charge et briefing" },
      { time: "09:30", activity: "Visite des boutiques et ateliers sélectionnés" },
      { time: "12:00", activity: "Temps libre pour les achats" },
      { time: "13:00", activity: "Retour à l'hôtel" },
    ],
  },
  "local-markets": {
    title: "Visite des marchés locaux",
    shortTitle: "Marchés locaux",
    description:
      "Vivez l'ambiance colorée des marchés d'Arusha : produits frais, épices, tissus et le rythme quotidien de la vie locale tanzanienne.",
    highlight: "Immersion au cœur des marchés locaux",
    duration: "Demi-journée",
    location: "Arusha",
    highlights: [
      "Promenade dans le marché central",
      "Épices et produits frais",
      "Textiles et artisanat",
      "Dégustations de spécialités locales",
      "Expérience idéale pour la photo",
    ],
    included: ["Guide local", "Visite du marché", "Transport", "Eau"],
    notIncluded: ["Achats alimentaires", "Shopping personnel", "Pourboires"],
    itinerary: [
      { time: "08:30", activity: "Prise en charge le matin" },
      { time: "09:00", activity: "Visite guidée des principales halles du marché" },
      { time: "11:00", activity: "Section épices et produits frais" },
      { time: "12:00", activity: "Retour à l'hôtel" },
    ],
  },
}

export const frZanzibarOverlays: Record<string, Partial<ZanzibarExperience>> = {
  "spice-tours": {
    title: "Tours des épices à Zanzibar",
    description:
      "Promenez-vous dans les plantations parfumées de Zanzibar et découvrez comment le clou de girofle, la vanille, la cannelle et la muscade ont façonné l'histoire et la cuisine de l'île.",
    highlight: "Expérience immersive dans une ferme d'épices",
    duration: "Demi-journée",
    price: "A partir de 45 $ par personne",
    highlights: [
      "Promenade guidée dans une plantation d'épices",
      "Dégustation de fruits tropicaux frais",
      "Découverte des usages traditionnels des épices",
      "Option déjeuner local disponible",
      "Parfait après un safari",
    ],
    included: ["Prise en charge à Stone Town", "Guide professionnel", "Entrée à la ferme d'épices", "Dégustation de fruits"],
    itinerary: [
      { step: "Prise en charge le matin", detail: "Transfert depuis votre hôtel ou Stone Town vers une ferme d'épices en activité." },
      { step: "Visite de la plantation", detail: "Balade guidée pour identifier épices, herbes et fruits tropicaux." },
      { step: "Dégustation et achats", detail: "Goûtez aux produits frais et découvrez les produits artisanaux à base d'épices." },
      { step: "Retour", detail: "Retour à votre hôtel ou continuation vers la plage." },
    ],
  },
  "cultural-tour": {
    title: "Visite culturelle de Stone Town",
    description:
      "Explorez Stone Town, classée à l'UNESCO, avec un guide local : portes sculptées, ruelles historiques, marchés et culture swahilie vivante.",
    highlight: "Balade patrimoniale dans Stone Town",
    duration: "Demi-journée",
    price: "A partir de 40 $ par personne",
    highlights: [
      "Visite historique à pied de Stone Town",
      "Vieux Fort et secteur House of Wonders",
      "Marchés locaux et ateliers artisanaux",
      "Architecture swahilie et portes sculptées",
      "Rythme flexible pour les photographes",
    ],
    included: ["Guide local professionnel", "Visite à pied de Stone Town", "Eau en bouteille"],
    itinerary: [
      { step: "Rencontre avec votre guide", detail: "Départ depuis un point central de Stone Town ou votre hôtel." },
      { step: "Balade patrimoniale", detail: "Visite des principaux monuments, marchés et cours cachées." },
      { step: "Haltes culturelles", detail: "Découverte des héritages arabe, perse, indien et africain de Zanzibar." },
      { step: "Temps libre", detail: "Suggestion de déjeuner puis retour à votre hôtel." },
    ],
  },
  "diving-snorkeling": {
    title: "Plongée et snorkeling à Zanzibar",
    description:
      "Découvrez l'atoll de Mnemba et les récifs coralliens de Zanzibar lors d'excursions guidées de snorkeling ou de plongée, avec équipement et transferts en bateau inclus.",
    highlight: "Récifs limpides de l'océan Indien",
    duration: "Journée complète",
    price: "A partir de 85 $ par personne",
    highlights: [
      "Sortie en bateau vers les sites de récif",
      "Équipement de snorkeling fourni",
      "Observation des dauphins selon la saison",
      "Déjeuner léger sur banc de sable",
      "Options plongée PADI sur demande",
    ],
    included: ["Transfert en bateau", "Équipement de snorkeling", "Guide", "Déjeuner léger", "Boissons"],
    itinerary: [
      { step: "Prise en charge à l'hôtel", detail: "Transfert matinal vers la plage de départ." },
      { step: "Excursion en bateau", detail: "Navigation vers Mnemba ou les récifs de la côte nord." },
      { step: "Sessions de snorkeling", detail: "Plusieurs arrêts pour explorer les récifs et nager." },
      { step: "Retour", detail: "Retour l'après-midi à votre hôtel balnéaire." },
    ],
  },
  transfers: {
    title: "Transferts aéroport et ferry à Zanzibar",
    description:
      "Transferts privés fiables entre l'aéroport international Abeid Amani Karume, les terminaux ferry, Stone Town et les resorts balnéaires de Zanzibar.",
    highlight: "Transferts insulaires porte-à-porte",
    duration: "Sur demande",
    price: "A partir de 35 $ par véhicule",
    highlights: [
      "Accueil personnalisé à l'aéroport",
      "Transferts depuis les terminaux ferry",
      "Liaisons resorts et Stone Town",
      "Suivi de vol inclus",
      "Assistance 24/7 de Gladiolus Tours",
    ],
    included: ["Véhicule privé", "Chauffeur anglophone", "Eau en bouteille", "Suivi des vols et ferries"],
    itinerary: [
      { step: "Réservation", detail: "Partagez vos détails de vol ou de ferry lors de la confirmation." },
      { step: "Accueil", detail: "Le chauffeur vous attend avec une pancarte à votre nom." },
      { step: "Transfert direct", detail: "Trajet confortable vers votre hôtel ou le port." },
      { step: "Option retour", detail: "Réservez également votre transfert de départ." },
    ],
  },
}

export const frAdventureOverlays: Record<string, Partial<Adventure>> = {
  "kilimanjaro-northern-circuit": {
    title: "Trek de 9 jours du Kilimandjaro par le Northern Circuit",
    category: "Ascension en montagne",
    description:
      "Le Northern Circuit est l'itinéraire le plus panoramique du Kilimandjaro avec une excellente acclimatation. Attendez-vous à des crêtes alpines isolées, des vues sur les glaciers et un rythme d'ascension progressif.",
    highlights: [
      "Fenêtre d'acclimatation la plus longue pour maximiser les chances de sommet",
      "Versants nord avec moins de randonneurs",
      "Équipe dédiée pour l'assistance sommet",
      "Option de camp privé au cratère",
    ],
    itinerary: [
      { day: 1, title: "Arrivée et vérification du matériel", description: "Arrivée à Arusha, rencontre avec votre guide principal et briefing complet sur l'équipement et la sécurité." },
      { day: 2, title: "Lemosho Gate - Mti Mkubwa", description: "Randonnée à travers la forêt tropicale jusqu'au premier camp, avec un rythme d'acclimatation progressif." },
      { day: 3, title: "Exploration du plateau de Shira", description: "Traversée des landes ouvertes avec de superbes vues sur le plateau de Shira et les sommets environnants." },
      { day: 4, title: "Acclimatation à Lava Tower", description: "Montée vers Lava Tower pour l'acclimatation puis descente vers un camp plus bas pour le repos." },
      { day: 5, title: "Traversée du Northern Circuit", description: "Traversée du versant nord, plus calme, au cœur de paysages alpins spectaculaires." },
      { day: 6, title: "Camp d'altitude et briefing sommet", description: "Arrivée au camp d'altitude, hydratation et préparation pour l'ascension nocturne." },
      { day: 7, title: "Jour du sommet", description: "Ascension de nuit vers Uhuru Peak puis descente vers le camp intermédiaire pour récupérer." },
      { day: 8, title: "Descente vers Mweka", description: "Descente à travers landes et forêt tropicale avec débriefing de fin d'ascension." },
      { day: 9, title: "Départ", description: "Transfert de retour vers Arusha ou extension safari." },
    ],
    packages: [
      { name: "Northern Circuit classique", duration: "9 jours", price: "A partir de 3 950 $", description: "Trek équilibré avec camps premium, équipe complète de guides et transferts privés.", includes: ["Frais de parc", "Pension complète", "Tentes privées", "Certificats de sommet"] },
      { name: "Northern Circuit + safari", duration: "12 jours", price: "A partir de 5 900 $", description: "Ajoutez trois jours de safari à Tarangire et au Ngorongoro après le sommet.", includes: ["Séjours en lodge safari", "Véhicule 4x4", "Safari en pension complète", "Frais de parc"] },
    ],
  },
  "walking-safaris": {
    title: "Safaris à pied et rencontres avec des guides autochtones",
    category: "Safaris à pied",
    description:
      "Prenez le temps d'explorer à pied avec des rangers spécialisés et des guides autochtones. Suivez les traces de la faune, apprenez les techniques du bush et profitez d'apéritifs intimes en pleine nature.",
    highlights: [
      "Suivi de traces et apprentissage du bushcraft",
      "Itinéraires de marche à faible impact",
      "Apéritifs au coucher du soleil au bord de la rivière",
      "Veillées de contes communautaires",
    ],
    itinerary: [
      { day: 1, title: "Arrivée et briefing ranger", description: "Rencontrez votre équipe de guides et découvrez les règles de sécurité et les bases du pistage." },
      { day: 2, title: "Pistage matinal et signes de faune", description: "Suivez des traces fraîches et apprenez à identifier les espèces et leurs habitats." },
      { day: 3, title: "Immersion avec les guides autochtones", description: "Passez du temps avec des guides autochtones pour découvrir écologie locale et traditions culturelles." },
      { day: 4, title: "Marche le long de la rivière et sundowner", description: "Explorez les couloirs d'eau puis détendez-vous autour d'un apéritif raffiné au bord de la rivière." },
      { day: 5, title: "Départ ou safari complémentaire", description: "Transfert vers la suite de votre voyage ou extension en safari en véhicule." },
    ],
    packages: [
      { name: "Essentiels du safari à pied", duration: "5 jours", price: "A partir de 2 150 $", description: "Marches guidées avec lodges boutique et briefings quotidiens.", includes: ["Permis de marche", "Ranger expert", "Tous les repas", "Transferts"] },
      { name: "Marche + fly camp", duration: "6 jours", price: "A partir de 2 950 $", description: "Inclut une nuit sous les étoiles avec une équipe de fly camp.", includes: ["Installation du fly camp", "Chef privé", "Veilleur de nuit", "Lodges de luxe"] },
    ],
  },
  "zanzibar-coast": {
    title: "Côte de Zanzibar et culture des épices",
    category: "Séjour balnéaire",
    description:
      "Détendez-vous sur la côte aux épices avec des visites de Stone Town, des croisières en dhow et des séjours boutique mêlant culture et ressourcement.",
    highlights: [
      "Balades patrimoniales à Stone Town",
      "Tour privé d'une ferme d'épices",
      "Navigation en dhow au coucher du soleil",
      "Spa et bien-être",
    ],
    itinerary: [
      { day: 1, title: "Arrivée à Stone Town", description: "Installation dans un hôtel patrimonial puis découverte gastronomique guidée en soirée." },
      { day: 2, title: "Ferme d'épices et culture", description: "Visite d'une plantation d'épices et des sites culturels avec un guide historien." },
      { day: 3, title: "Transfert vers la plage", description: "Installation sur la côte pour profiter de la plage, du snorkeling et du spa." },
      { day: 4, title: "Expériences océaniques", description: "Croisière privée en dhow, snorkeling sur récif et dîner de fruits de mer." },
      { day: 5, title: "Départ", description: "Matinée libre puis transfert à l'aéroport." },
    ],
    packages: [
      { name: "Escapade côte aux épices", duration: "5 jours", price: "A partir de 1 900 $", description: "Hôtel patrimonial et retraite balnéaire avec expériences sélectionnées.", includes: ["Guide Stone Town", "Resort de plage", "Transferts aéroport", "Petits-déjeuners"] },
      { name: "Romance sur la côte", duration: "6 jours", price: "A partir de 2 450 $", description: "Ajoutez dîners privés, rituels spa et navigation au coucher du soleil.", includes: ["Dîner privé par un chef", "Soins spa", "Croisière en dhow", "Service majordome"] },
    ],
  },
  "northern-circuit-adventure": {
    title: "Safaris aventure sur le circuit nord",
    category: "Safaris aventure",
    description:
      "Combinez safaris en véhicule et activités dynamiques - canoë, vélo, randonnées sur le rebord du cratère et journées photo adaptées à la meilleure saison animalière.",
    highlights: [
      "Safaris en canoë au lac Manyara",
      "Randonnées sur le rebord du cratère",
      "Sessions de coaching photo",
      "4x4 privé avec itinéraire flexible",
    ],
    itinerary: [
      { day: 1, title: "Arrivée et orientation à Arusha", description: "Briefing de bienvenue avec votre directeur safari et préparation de l'équipement." },
      { day: 2, title: "Safaris à Tarangire", description: "Sorties le matin et le soir avec excursion à vélo en option." },
      { day: 3, title: "Canoë au lac Manyara", description: "Safari en canoë puis rencontres culturelles au village." },
      { day: 4, title: "Marche sur le rebord du Ngorongoro", description: "Randonnée guidée sur le bord du cratère avec déjeuner pique-nique." },
      { day: 5, title: "Photographie au Serengeti", description: "Sessions photo à l'heure dorée avec guides experts." },
      { day: 6, title: "Départ ou extension", description: "Extension vers Zanzibar ou départ via l'aéroport du Kilimandjaro." },
    ],
    packages: [
      { name: "Aventure nord essentielle", duration: "6 jours", price: "A partir de 3 200 $", description: "Safari actif avec guide privé et rythme quotidien flexible.", includes: ["Guide privé", "Camps de luxe", "Tous les repas", "Frais de parc"] },
      { name: "Aventure nord + Zanzibar", duration: "9 jours", price: "A partir de 4 850 $", description: "Ajoutez trois jours de plage à Zanzibar et des étapes culturelles sélectionnées.", includes: ["Resort de plage", "Transferts sur l'île", "Croisière en dhow", "Dîner chef"] },
    ],
  },
}

export const frDestinationOverlays: Record<string, Partial<Destination>> = {
  "serengeti-national-park": {
    title: "Parc national du Serengeti",
    location: "Tanzanie",
    duration: "5 jours",
    price: "A partir de 2 500 $",
    description: "Découvrez le célèbre écosystème du Serengeti, berceau de la Grande Migration et d'une faune abondante comprenant lions, léopards, éléphants et guépards.",
    highlights: ["Observer la Grande Migration", "Safari Big Five", "Vol en montgolfière au lever du soleil", "Visite de villages masaï", "Opportunités photo animalières"],
    itinerary: [
      { day: 1, title: "Arrivée et transfert au Serengeti", description: "Accueil à l'aéroport du Kilimandjaro puis transfert au Serengeti. Safari en soirée." },
      { day: 2, title: "Journée complète de safari", description: "Safaris matin et après-midi dans le Serengeti central avec déjeuner pique-nique." },
      { day: 3, title: "Safari en montgolfière", description: "Vol optionnel à l'aube suivi d'un petit-déjeuner au champagne. Safari l'après-midi." },
      { day: 4, title: "Expérience culturelle masaï", description: "Visite d'un village masaï traditionnel puis safari en soirée." },
      { day: 5, title: "Dernier safari et départ", description: "Safari matinal puis retour à Arusha." },
    ],
    included: ["Transferts aéroport", "Hébergement en camp de luxe", "Tous les repas pendant le safari", "Guide professionnel et véhicule 4x4", "Frais de parc", "Eau en bouteille"],
    excluded: ["Vols internationaux", "Assurance voyage", "Dépenses personnelles", "Vol en montgolfière (550 $)", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 8 personnes",
  },
  "ngorongoro-crater": {
    title: "Cratère du Ngorongoro",
    location: "Tanzanie",
    duration: "4 jours",
    price: "A partir de 2 000 $",
    description: "Explorez la plus grande caldeira volcanique intacte du monde, un sanctuaire naturel avec l'une des plus fortes densités animales d'Afrique.",
    highlights: ["Safaris sur le fond du cratère", "Observation de rhinocéros noirs", "Site archéologique d'Olduvai", "Vues volcaniques spectaculaires", "Flamants de Lake Magadi"],
    itinerary: [
      { day: 1, title: "Arrivée et bord du cratère", description: "Transfert d'Arusha au Ngorongoro. Soirée en lodge avec vue sur le cratère." },
      { day: 2, title: "Safari au fond du cratère", description: "Descente de 600 m pour une journée de safari complète avec déjeuner pique-nique." },
      { day: 3, title: "Olduvai Gorge et visite culturelle", description: "Visite du site archéologique et expérience culturelle masaï." },
      { day: 4, title: "Départ", description: "Temps libre le matin puis retour à Arusha." },
    ],
    included: ["Tous les transferts", "Hébergement en lodge", "Tous les repas", "Frais et permis du cratère", "Guide professionnel", "Descente dans le cratère"],
    excluded: ["Vols internationaux", "Boissons alcoolisées", "Assurance voyage", "Articles personnels", "Pourboires"],
    bestTime: "Toute l'année",
    groupSize: "2 à 6 personnes",
  },
  "tarangire-national-park": {
    title: "Parc national de Tarangire",
    location: "Tanzanie",
    duration: "3 jours",
    price: "A partir de 1 500 $",
    description: "Célèbre pour ses grands troupeaux d'éléphants et ses baobabs anciens, Tarangire offre des rencontres animalières intimistes dans un décor remarquable.",
    highlights: ["Importantes populations d'éléphants", "Baobabs ancestraux", "Lions grimpeurs", "Plus de 550 espèces d'oiseaux", "Safaris à pied disponibles"],
    itinerary: [
      { day: 1, title: "Arusha - Tarangire", description: "Route matinale vers Tarangire puis safari l'après-midi." },
      { day: 2, title: "Journée complète de safari", description: "Exploration du parc avec déjeuner pique-nique et option de safari à pied." },
      { day: 3, title: "Safari matinal et retour", description: "Dernier safari tôt le matin puis retour à Arusha." },
    ],
    included: ["Transport en 4x4", "Hébergement en lodge", "Tous les repas", "Frais de parc", "Guide professionnel"],
    excluded: ["Vols internationaux", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 6 personnes",
  },
  "lake-manyara-national-park": {
    title: "Parc national du lac Manyara",
    location: "Tanzanie",
    duration: "2 jours",
    price: "A partir de 900 $",
    description: "Petit parc aux habitats variés, de la forêt alimentée par des sources au lac alcalin, réputé pour ses lions grimpeurs.",
    highlights: ["Lions grimpeurs", "Volées de flamants sur le lac", "Éléphants de forêt", "Passerelle dans la canopée", "Sources chaudes"],
    itinerary: [
      { day: 1, title: "Arrivée et safari", description: "Transfert vers le lac Manyara puis safari l'après-midi dans la forêt et au bord du lac." },
      { day: 2, title: "Canopy walk et départ", description: "Passerelle matinale dans la canopée, dernier safari puis retour à Arusha." },
    ],
    included: ["Tous les transports", "Hébergement en lodge", "Repas", "Entrée au parc", "Services de guide"],
    excluded: ["Vols", "Assurance", "Articles personnels", "Pourboires"],
    bestTime: "Toute l'année",
    groupSize: "2 à 6 personnes",
  },
  "mount-kilimanjaro-trek": {
    title: "Trek du mont Kilimandjaro",
    location: "Tanzanie",
    duration: "8 jours",
    price: "A partir de 4 500 $",
    description: "Atteignez le toit de l'Afrique par la magnifique voie de Lemosho, réputée pour son excellente acclimatation et son fort taux de réussite.",
    highlights: ["Atteindre Uhuru Peak à 5 895 m", "Traverser plusieurs zones climatiques", "Vues montagneuses spectaculaires", "Guides de montagne professionnels", "Fort taux de réussite au sommet"],
    itinerary: [
      { day: 1, title: "Londorossi Gate - Mti Mkubwa", description: "Formalités puis marche en forêt tropicale jusqu'au premier camp." },
      { day: 2, title: "Mti Mkubwa - Shira 1", description: "Montée vers le plateau de Shira à travers les landes." },
      { day: 3, title: "Shira 1 - Shira 2", description: "Journée d'acclimatation à travers le plateau de Shira." },
      { day: 4, title: "Shira 2 - Barranco", description: "Montée jusqu'à Lava Tower puis descente pour favoriser l'acclimatation." },
      { day: 5, title: "Barranco - Karanga", description: "Ascension du Barranco Wall puis traversée vers Karanga Camp." },
      { day: 6, title: "Karanga - Barafu", description: "Courte montée vers le camp d'altitude puis préparation pour le sommet." },
      { day: 7, title: "Jour du sommet", description: "Départ de nuit pour Uhuru Peak puis descente à Mweka Camp." },
      { day: 8, title: "Mweka - Gate", description: "Descente finale en forêt et remise des certificats." },
    ],
    included: ["Permis de montagne", "Équipement de camping", "Tous les repas en montagne", "Guides et porteurs professionnels", "Frais de secours"],
    excluded: ["Vols internationaux", "Visa", "Assurance voyage", "Équipement personnel", "Pourboires de l'équipe"],
    bestTime: "Janvier-mars, juin-octobre",
    groupSize: "2 à 12 personnes",
  },
  "ruaha-national-park": {
    title: "Parc national de Ruaha",
    location: "Tanzanie",
    duration: "4 jours",
    price: "A partir de 2 200 $",
    description: "Découvrez le sud sauvage de la Tanzanie : paysages de rivière, très peu de véhicules et excellentes observations de prédateurs dans l'isolement de Ruaha.",
    highlights: ["Safaris éloignés des foules", "Excellentes observations de lions et léopards", "Ornithologie le long de la Grande Ruaha", "Marches guidées dans certaines zones", "Sundowners spectaculaires en brousse"],
    itinerary: [
      { day: 1, title: "Arrivée en avion et safari du soir", description: "Arrivée sur la piste, installation au camp puis safari à l'heure dorée." },
      { day: 2, title: "Journée complète à Ruaha", description: "Safaris matin et après-midi entre lits de rivière et plaines boisées avec déjeuner brousse." },
      { day: 3, title: "Option safari à pied", description: "Marche guidée optionnelle pour les traces et l'écologie suivie d'un safari l'après-midi." },
      { day: 4, title: "Dernier safari et départ", description: "Safari matinal puis transfert vers la piste d'atterrissage." },
    ],
    included: ["Frais de parc", "Hébergement", "Repas", "Guide professionnel", "Safaris", "Transferts à Ruaha"],
    excluded: ["Vols", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 6 personnes",
  },
  "nyerere-national-park": {
    title: "Parc national de Nyerere",
    location: "Tanzanie",
    duration: "3 jours",
    price: "A partir de 1 850 $",
    description: "Explorez l'écosystème de la rivière Rufiji avec une combinaison de safaris classiques et d'aventures nautiques dans l'une des plus vastes aires protégées d'Afrique.",
    highlights: ["Safaris en bateau sur la Rufiji", "Très bonnes observations d'éléphants et d'hippopotames", "Options de safari à pied", "Rythme détendu avec peu de véhicules", "Superbes couchers de soleil sur la rivière"],
    itinerary: [
      { day: 1, title: "Arrivée et croisière fluviale", description: "Arrivée et installation au camp puis safari en bateau en fin d'après-midi." },
      { day: 2, title: "Safaris en véhicule", description: "Safari matinal sur les plaines inondables puis sortie l'après-midi vers les points d'eau." },
      { day: 3, title: "Activité matinale et départ", description: "Petite marche optionnelle ou dernier safari puis transfert vers votre correspondance." },
    ],
    included: ["Hébergement", "Repas", "Frais de parc", "Safari en bateau", "Safaris", "Services de guide"],
    excluded: ["Vols", "Assurance voyage", "Achats personnels", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 8 personnes",
  },
  "zanzibar-island-escape": {
    title: "Escapade sur l'île de Zanzibar",
    location: "Tanzanie",
    duration: "4 jours",
    price: "A partir de 1 300 $",
    description: "Terminez votre safari entre brises marines, croisières en dhow et matinées paisibles sur les plages de sable blanc de Zanzibar.",
    highlights: ["Détente en bord de mer", "Découverte de Stone Town", "Snorkeling et excursions récifales", "Croisière en dhow au coucher du soleil", "Cuisine swahilie et tours des épices"],
    itinerary: [
      { day: 1, title: "Arrivée et plage", description: "Transfert à votre hôtel et installation au rythme de l'île avec baignade au coucher du soleil." },
      { day: 2, title: "Stone Town et culture", description: "Explorez ruelles et marchés de Stone Town puis soirée tranquille en bord de mer." },
      { day: 3, title: "Excursion en mer", description: "Snorkeling, pique-nique sur banc de sable ou croisière selon les conditions et vos envies." },
      { day: 4, title: "Départ", description: "Dernière matinée à la plage puis transfert à l'aéroport." },
    ],
    included: ["Transferts", "Hébergement", "Petit-déjeuner", "Excursions sélectionnées"],
    excluded: ["Vols", "Déjeuners et dîners", "Assurance voyage", "Dépenses personnelles"],
    bestTime: "Juin à mars",
    groupSize: "2 à 8 personnes",
  },
  "saadani-national-park": {
    title: "Parc national de Saadani",
    location: "Tanzanie",
    duration: "3 jours",
    price: "A partir de 1 600 $",
    description: "Là où la brousse rencontre la plage : Saadani mêle paysages côtiers et observation animalière pour une extension unique en Tanzanie.",
    highlights: ["Paysages de safari côtiers", "Safaris avec vue sur la mer", "Sorties en bateau et faune de rivière", "Atmosphère paisible et peu fréquentée", "Idéal pour une courte extension"],
    itinerary: [
      { day: 1, title: "Arrivée et safari de l'après-midi", description: "Arrivée puis safari à travers plaines côtières et corridors fluviaux." },
      { day: 2, title: "Safari et option rivière", description: "Safari matinal puis excursion fluviale optionnelle selon la saison." },
      { day: 3, title: "Dernière matinée et départ", description: "Courte activité matinale puis transfert de départ." },
    ],
    included: ["Hébergement", "Repas", "Frais de parc", "Safaris", "Services de guide"],
    excluded: ["Vols", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 8 personnes",
  },
  "mahale-mountains-national-park": {
    title: "Parc national des monts Mahale",
    location: "Tanzanie",
    duration: "5 jours",
    price: "A partir de 3 400 $",
    description: "Envolez-vous vers le lac Tanganyika pour un trekking chimpanzé à Mahale, l'une des expériences les plus riches et isolées de Tanzanie.",
    highlights: ["Trekking chimpanzé", "Paysages du lac Tanganyika", "Randonnée en montagne forestière", "Aventure aérienne dans une zone reculée", "Parfait pour les amoureux de nature"],
    itinerary: [
      { day: 1, title: "Arrivée et bord du lac", description: "Arrivée en avion ou bateau, installation et découverte des rives du lac." },
      { day: 2, title: "Trek chimpanzé", description: "Marche matinale à la recherche des chimpanzés avec des pisteurs experts." },
      { day: 3, title: "Deuxième trek ou randonnée", description: "Choisissez un nouveau trek ou une randonnée plus longue selon les conditions." },
      { day: 4, title: "Temps au lac", description: "Détente avec baignade, kayak ou excursion douce en bateau." },
      { day: 5, title: "Départ", description: "Transfert vers la suite de votre voyage." },
    ],
    included: ["Frais de parc", "Hébergement", "Repas", "Trekking chimpanzé", "Transferts locaux"],
    excluded: ["Vols", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 6 personnes",
  },
  "lake-natron": {
    title: "Lac Natron",
    location: "Tanzanie",
    duration: "2 jours",
    price: "A partir de 750 $",
    description: "Découvrez l'un des paysages les plus spectaculaires d'Afrique de l'Est : eaux alcalines remplies de flamants, décor volcanique et porte d'entrée vers l'Ol Doinyo Lengai.",
    highlights: ["Colonies de flamants nains", "Paysages volcaniques", "Cascades et culture masaï", "Circuit nord hors des sentiers battus", "Excellentes opportunités photo"],
    itinerary: [
      { day: 1, title: "Arusha - lac Natron", description: "Route panoramique via des villages masaï avec arrêts aux cascades et points de vue." },
      { day: 2, title: "Rive du lac et retour", description: "Matinée au bord du lac pour les flamants et les paysages puis retour à Arusha." },
    ],
    included: ["Transport", "Hébergement", "Repas", "Services de guide", "Frais de conservation"],
    excluded: ["Vols", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Juin à octobre",
    groupSize: "2 à 6 personnes",
  },
  "arusha-national-park": {
    title: "Parc national d'Arusha",
    location: "Tanzanie",
    duration: "1 jour",
    price: "A partir de 350 $",
    description: "Un joyau compact au pied du mont Meru - girafes, buffles, colobes et lacs de cratère à quelques minutes seulement d'Arusha.",
    highlights: ["Vue sur le mont Meru", "Points de vue sur le cratère de Ngurdoto", "Avifaune des lacs Momella", "Safaris à pied disponibles", "Idéal pour s'acclimater avant le Kilimandjaro"],
    itinerary: [
      { day: 1, title: "Safari d'une journée", description: "Prise en charge le matin, safari entre forêt et lacs, déjeuner pique-nique, observation de la faune puis retour à Arusha." },
    ],
    included: ["Frais de parc", "Véhicule privé 4x4", "Guide professionnel", "Déjeuner pique-nique", "Transferts hôtel"],
    excluded: ["Vols", "Assurance voyage", "Dépenses personnelles", "Pourboires"],
    bestTime: "Toute l'année",
    groupSize: "2 à 6 personnes",
  },
}

export const frTrekOverlays: Record<string, Partial<Trek>> = {
  "kilimanjaro-marangu-route": {
    title: "Voie Marangu",
    headline: "Voie Marangu en 5 jours - Ascension du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "5 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "La seule voie du Kilimandjaro avec hébergement en refuge. Idéale pour les débutants recherchant du confort et un itinéraire plus court vers le sommet.",
    overview: "La voie Marangu est la manière la plus établie et la plus confortable de gravir le Kilimandjaro. C'est la seule route avec hébergement en refuge collectif, parfaite pour les randonneurs qui préfèrent éviter le camping. Le sentier traverse forêt tropicale, landes, désert alpin puis atteint Uhuru Peak (5 895 m), le point culminant d'Afrique.",
    priceFrom: "2 100 $ par personne",
    highlights: ["Seule voie avec hébergement en refuge", "Idéale pour les débutants", "Sentier progressif et bien entretenu", "Ascension classique via Gilman's Point", "Refuges confortables à chaque camp"],
    whyChoose: ["Hébergement en refuge plutôt qu'en tente", "Durée plus courte et logistique simple", "Convient à une condition physique modérée", "Bon taux de réussite avec un rythme adapté"],
    itinerary: [
      { day: "Jour 1", title: "Marangu Gate - Mandara Hut", description: "Début de l'ascension à travers la forêt tropicale luxuriante jusqu'à Mandara Hut (2 700 m)." },
      { day: "Jour 2", title: "Mandara Hut - Horombo Hut", description: "Montée vers les landes avec vues spectaculaires sur Mawenzi et Kibo jusqu'à Horombo Hut (3 720 m)." },
      { day: "Jour 3", title: "Horombo Hut - Kibo Hut", description: "Traversée du désert alpin entre Mawenzi et Kibo puis arrivée à Kibo Hut (4 700 m)." },
      { day: "Jour 4", title: "Sommet et descente vers Horombo", description: "Ascension nocturne vers Uhuru Peak au lever du soleil puis descente à Horombo Hut." },
      { day: "Jour 5", title: "Horombo Hut - Marangu Gate", description: "Descente finale en forêt et remise du certificat." },
    ],
  },
  "kilimanjaro-machame-route": {
    title: "Voie Machame",
    headline: "Voie Machame en 7 jours - Ascension du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "7 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "La voie la plus populaire du Kilimandjaro, offrant des paysages spectaculaires et une excellente acclimatation grâce au principe 'monter haut, dormir bas'.",
    overview: "Surnommée la voie du Whisky, Machame est le sentier le plus populaire du Kilimandjaro. Son excellent profil d'acclimatation en fait l'une des routes avec les meilleurs taux de réussite au sommet.",
    priceFrom: "2 200 $ par personne",
    highlights: ["Voie la plus populaire du Kilimandjaro", "Excellent profil d'acclimatation", "Paysages variés de la forêt aux glaciers", "Ascension emblématique du Barranco Wall", "Fort taux de réussite"],
    whyChoose: ["Meilleur équilibre entre défi et récompense", "Idéale pour les trekkers aventuriers", "Paysages variés et photogéniques", "Solides statistiques de réussite au sommet"],
    itinerary: [
      { day: "Jour 1", title: "Machame Gate - Machame Camp", description: "Marche à travers une forêt dense jusqu'à Machame Camp (3 000 m)." },
      { day: "Jour 2", title: "Machame Camp - Shira 2", description: "Montée raide vers les landes et traversée du plateau de Shira jusqu'à 3 850 m." },
      { day: "Jour 3", title: "Shira 2 - Lava Tower - Barranco", description: "Journée d'acclimatation via Lava Tower avant de descendre dans la vallée de Barranco." },
      { day: "Jour 4", title: "Barranco - Karanga", description: "Ascension du Barranco Wall puis traversée vers Karanga Camp." },
      { day: "Jour 5", title: "Karanga - Barafu", description: "Montée à Barafu Camp, base de départ pour la nuit du sommet." },
      { day: "Jour 6", title: "Sommet et Mweka Camp", description: "Ascension de nuit vers Uhuru Peak puis descente jusqu'à Mweka Camp." },
      { day: "Jour 7", title: "Mweka Camp - Mweka Gate", description: "Descente finale en forêt et retour vers Arusha ou Moshi." },
    ],
  },
  "kilimanjaro-lemosho-route": {
    title: "Voie Lemosho",
    headline: "Voie Lemosho en 8 jours - Ascension panoramique du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "8 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "L'une des plus belles routes du Kilimandjaro, avec moins d'affluence, un départ sauvage et l'un des meilleurs taux de réussite.",
    overview: "La voie Lemosho est souvent considérée comme la plus belle manière de gravir le Kilimandjaro. Elle démarre sur les pentes ouest, traverse le vaste plateau de Shira et offre une acclimatation progressive exceptionnelle.",
    priceFrom: "2 380 $ par personne",
    highlights: ["Voie la plus panoramique", "Faible fréquentation", "Excellent programme d'acclimatation", "Très fort taux de réussite", "Approche sauvage par l'ouest"],
    whyChoose: ["Expérience premium", "Idéale pour les grimpeurs sérieux", "Moins fréquentée que Machame", "Acclimatation plus longue pour plus de sécurité"],
    itinerary: [
      { day: "Jour 1", title: "Londorossi Gate - Mti Mkubwa", description: "Départ en forêt tropicale sur le versant ouest jusqu'à Mti Mkubwa (2 750 m)." },
      { day: "Jour 2", title: "Mti Mkubwa - Shira 1", description: "Sortie de la forêt vers les landes jusqu'à Shira 1 Camp (3 500 m)." },
      { day: "Jour 3", title: "Shira 1 - Shira 2", description: "Marche douce sur le plateau de Shira avec vues sur le mont Meru et Kibo." },
      { day: "Jour 4", title: "Shira 2 - Lava Tower - Barranco", description: "Montée vers Lava Tower pour l'acclimatation puis descente vers Barranco." },
      { day: "Jour 5", title: "Barranco - Karanga", description: "Passage du Barranco Wall puis traversée vers Karanga Camp." },
      { day: "Jour 6", title: "Karanga - Barafu", description: "Arrivée à Barafu Camp et préparation pour la nuit du sommet." },
      { day: "Jour 7", title: "Sommet et Mweka Camp", description: "Ascension nocturne vers Uhuru Peak via Stella Point puis descente vers Mweka." },
      { day: "Jour 8", title: "Mweka Camp - Mweka Gate", description: "Descente finale en forêt et célébration de votre réussite." },
    ],
  },
  "kilimanjaro-rongai-route": {
    title: "Voie Rongai",
    headline: "Voie Rongai en 6 jours - Approche nord du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "6 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "La seule voie qui aborde le Kilimandjaro par le nord, proche du Kenya. Calme, sèche et idéale pour une expérience plus sauvage.",
    overview: "Rongai est la seule route qui approche le Kilimandjaro depuis le nord, près de la frontière kenyane. Plus sèche et moins fréquentée, elle convient très bien pendant les saisons humides.",
    priceFrom: "2 150 $ par personne",
    highlights: ["Voie la moins fréquentée", "Conditions plus sèches toute l'année", "Montée progressive", "Superbes panoramas côté nord", "Possibilités d'observer la faune sur les basses pentes"],
    whyChoose: ["Idéale pendant la saison des pluies", "Moins de trafic que les routes du sud", "Pente régulière", "Atmosphère plus sauvage"],
    itinerary: [
      { day: "Jour 1", title: "Rongai Gate - Simba Camp", description: "Début à travers les pentes boisées du nord jusqu'à Simba Camp (2 650 m)." },
      { day: "Jour 2", title: "Simba Camp - Kikelewa Camp", description: "Montée dans les landes avec vues sur Mawenzi et les plaines du nord." },
      { day: "Jour 3", title: "Kikelewa - Mawenzi Tarn", description: "Montée dans une vallée alpine spectaculaire jusqu'à Mawenzi Tarn (4 330 m)." },
      { day: "Jour 4", title: "Mawenzi Tarn - Kibo Hut", description: "Traversée du désert alpin jusqu'à Kibo Hut (4 700 m)." },
      { day: "Jour 5", title: "Sommet et Horombo Hut", description: "Ascension nocturne vers Uhuru Peak via Gilman's Point puis descente vers Horombo." },
      { day: "Jour 6", title: "Horombo Hut - Marangu Gate", description: "Descente finale en forêt et remise du certificat." },
    ],
  },
  "umbwe-route": {
    title: "Voie Umbwe",
    headline: "Voie Umbwe en 6 jours - Ascension raide du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "6 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "La voie la plus raide et la plus directe du Kilimandjaro. Recommandée aux trekkers expérimentés en quête de défi.",
    overview: "La voie Umbwe est l'itinéraire le plus abrupt du Kilimandjaro. Elle monte rapidement à travers la forêt et les crêtes avant de rejoindre le circuit sud à Barranco.",
    priceFrom: "2 150 $ par personne",
    highlights: ["Montée raide et directe", "Moins fréquentée", "Accès rapide à la vallée de Barranco", "Progression sur crêtes", "Expérience très sportive"],
    whyChoose: ["Chemin le plus direct vers le sommet", "Idéale pour les randonneurs expérimentés", "Ambiance plus sauvage", "Crêtes spectaculaires"],
    itinerary: [
      { day: "Jour 1", title: "Umbwe Gate - Umbwe Cave Camp", description: "Montée raide en forêt dense jusqu'à Umbwe Cave (2 940 m)." },
      { day: "Jour 2", title: "Umbwe Cave - Barranco Camp", description: "Poursuite de la montée sur la crête avec vues saisissantes puis arrivée à Barranco." },
      { day: "Jour 3", title: "Barranco - Karanga", description: "Ascension du Barranco Wall puis traversée vers Karanga Camp." },
      { day: "Jour 4", title: "Karanga - Barafu", description: "Montée à Barafu Camp puis repos avant l'effort final." },
      { day: "Jour 5", title: "Sommet et Mweka Camp", description: "Ascension vers Uhuru Peak puis descente à Mweka Camp." },
      { day: "Jour 6", title: "Mweka Camp - Mweka Gate", description: "Descente finale en forêt et retour à l'hôtel." },
    ],
  },
  "shira-route": {
    title: "Voie Shira",
    headline: "Voie Shira en 7 jours - Trek occidental du Kilimandjaro",
    location: "Parc national du Kilimandjaro, Tanzanie",
    duration: "7 jours",
    elevation: "5 895 m (Uhuru Peak)",
    bestTime: "Juin - octobre et janvier - mars",
    permits: "Permis du parc national du Kilimandjaro requis",
    description: "Une approche panoramique par l'ouest qui commence en altitude sur le plateau de Shira. Très beaux paysages et bonne acclimatation.",
    overview: "La voie Shira commence à haute altitude sur le versant ouest du Kilimandjaro, offrant un accès immédiat au plateau de Shira et à des panoramas exceptionnels avant de rejoindre les itinéraires Machame et Lemosho.",
    priceFrom: "2 300 $ par personne",
    highlights: ["Traversée panoramique du plateau de Shira", "Départ occidental plus reculé", "Superbes paysages ouverts", "Bon taux de réussite", "Moins d'affluence au départ"],
    whyChoose: ["Immersion rapide en haute altitude", "Bon potentiel d'acclimatation", "Magnifiques paysages de plateau", "Approche ouest plus tranquille"],
    itinerary: [
      { day: "Jour 1", title: "Shira Gate - Shira 1", description: "Départ en altitude à travers les landes jusqu'à Shira 1 Camp." },
      { day: "Jour 2", title: "Shira 1 - Shira 2", description: "Marche douce sur le plateau avec vues sur Kibo et le mont Meru." },
      { day: "Jour 3", title: "Shira 2 - Barranco via Lava Tower", description: "Montée vers Lava Tower puis descente vers Barranco Camp." },
      { day: "Jour 4", title: "Barranco - Karanga", description: "Ascension du Barranco Wall puis poursuite vers Karanga." },
      { day: "Jour 5", title: "Karanga - Barafu", description: "Montée à Barafu Camp et préparation pour l'ascension nocturne." },
      { day: "Jour 6", title: "Sommet et Mweka Camp", description: "Ascension vers Uhuru Peak via Stella Point puis descente vers Mweka." },
      { day: "Jour 7", title: "Mweka Camp - Mweka Gate", description: "Descente finale à travers la forêt tropicale." },
    ],
  },
  "mount-meru-trek": {
    title: "Trek du mont Meru",
    headline: "Trek du mont Meru en 4 jours - Parc national d'Arusha",
    location: "Parc national d'Arusha, Tanzanie",
    duration: "4 jours",
    elevation: "4 566 m (Socialist Peak)",
    bestTime: "Juin - octobre et janvier - février",
    permits: "Frais de parc et ranger armé requis",
    description: "Le deuxième plus haut sommet de Tanzanie et un excellent trek d'acclimatation avant le Kilimandjaro.",
    overview: "Le trek du mont Meru est une superbe aventure de 4 jours dans le parc national d'Arusha. Il combine observation de la faune sur les basses pentes et ascension spectaculaire du rebord du cratère jusqu'à Socialist Peak (4 566 m).",
    priceFrom: "1 000 $ par personne",
    highlights: ["Rencontres avec la faune sur les pentes basses", "Vues spectaculaires sur le cratère", "Parfaite acclimatation pour le Kilimandjaro", "Moins fréquenté", "Sommet au lever du soleil"],
    whyChoose: ["Excellente acclimatation avant le Kilimandjaro", "Faune abondante, dont buffles et girafes", "Paysages volcaniques impressionnants", "Plus court et plus abordable que le Kilimandjaro"],
    itinerary: [
      { day: "Jour 1", title: "Momella Gate - Miriakamba Hut", description: "Montée à travers forêt et prairies avec observations de faune jusqu'à Miriakamba Hut (2 514 m)." },
      { day: "Jour 2", title: "Miriakamba Hut - Saddle Hut", description: "Montée plus soutenue avec vues panoramiques sur le cratère et le Kilimandjaro." },
      { day: "Jour 3", title: "Sommet et retour à Miriakamba", description: "Ascension nocturne vers Socialist Peak puis descente vers Miriakamba Hut." },
      { day: "Jour 4", title: "Miriakamba Hut - Momella Gate", description: "Descente finale à travers le parc national d'Arusha puis retour à Arusha." },
    ],
  },
  "ol-doinyo-lengai-night-hike": {
    title: "Ascension nocturne de l'Ol Doinyo Lengai",
    headline: "Ascension du volcan actif Ol Doinyo Lengai",
    location: "Lac Natron, Tanzanie",
    duration: "1 nuit",
    elevation: "2 962 m",
    bestTime: "Juin - octobre",
    permits: "Guide local requis",
    description: "Grimpez de nuit le seul volcan actif de Tanzanie pour admirer des vues spectaculaires sur la vallée du Rift au lever du soleil.",
    overview: "L'Ol Doinyo Lengai est le seul volcan actif de Tanzanie et une montagne sacrée pour les Masaï. Cette ascension exigeante de nuit mène à un sommet offrant une vue imprenable sur la vallée du Rift, le lac Natron et le Kilimandjaro au loin.",
    priceFrom: "350 $ par personne",
    highlights: ["Ascension d'un volcan actif", "Sommet au lever du soleil", "Région culturelle masaï", "Aventure exigeante", "Milieu sauvage et isolé"],
  },
  "packing-list": {
    title: "Liste d'équipement pour le Kilimandjaro",
    headline: "Checklist essentielle pour le Kilimandjaro",
    location: "Mont Kilimandjaro, Tanzanie",
    duration: "Guide de préparation",
    elevation: "Jusqu'à 5 895 m",
    bestTime: "Toute l'année",
    permits: "Aucun permis requis pour ce guide",
    description: "Checklist complète pour gravir le Kilimandjaro en toute sécurité et avec confort.",
    overview: "Préparer le Kilimandjaro demande des vêtements adaptés, un bon système de couches, un équipement de couchage efficace et des accessoires essentiels. Le bon matériel améliore nettement vos chances d'atteindre le sommet dans de bonnes conditions.",
    highlights: ["Système de vêtements multicouches", "Sac de couchage haute altitude", "Équipement imperméable", "Bonnes chaussures de randonnée", "Lampe frontale et bâtons de marche"],
  },
  "altitude-acclimatization": {
    title: "Altitude et acclimatation",
    headline: "Comprendre l'altitude sur le Kilimandjaro",
    location: "Mont Kilimandjaro",
    duration: "Guide de préparation",
    elevation: "5 895 m",
    bestTime: "Toute l'année",
    permits: "Aucun permis requis",
    description: "Comprenez comment une bonne acclimatation augmente vos chances d'atteindre Uhuru Peak en sécurité.",
    overview: "Le mal aigu des montagnes est le principal défi sur le Kilimandjaro. Choisir une voie plus longue, bien s'hydrater et avancer à un rythme progressif améliore fortement les chances de réussite.",
    highlights: ["Principe 'monter haut, dormir bas'", "Importance de l'hydratation", "Stratégie de montée progressive", "Surveillance des symptômes du MAM"],
  },
  "best-time-to-climb": {
    title: "Meilleure période pour gravir le Kilimandjaro",
    headline: "Guide saisonnier pour l'ascension du Kilimandjaro",
    location: "Mont Kilimandjaro",
    duration: "Guide de préparation",
    elevation: "5 895 m",
    bestTime: "Janvier-mars et juin-octobre",
    permits: "Aucun permis requis",
    description: "Analyse saisonnière des conditions météo et des conditions de sommet sur le Kilimandjaro.",
    overview: "Le Kilimandjaro peut se gravir toute l'année, mais les saisons sèches offrent généralement une meilleure visibilité et des conditions plus sûres pour le sommet.",
    highlights: ["Avantages de la saison sèche", "Considérations pour la saison des pluies", "Températures attendues", "Niveau d'affluence selon les mois"],
  },
  "climbing-faqs": {
    title: "FAQ sur l'ascension du Kilimandjaro",
    headline: "Questions fréquentes sur le Kilimandjaro",
    location: "Mont Kilimandjaro",
    duration: "Guide d'information",
    elevation: "5 895 m",
    bestTime: "Toute l'année",
    permits: "Aucun permis requis",
    description: "Les questions les plus fréquentes sur l'ascension du Kilimandjaro, expliquées par nos experts montagne.",
    overview: "Retrouvez des réponses claires sur la condition physique nécessaire, l'entraînement, la sécurité, le mal d'altitude, les taux de réussite et la préparation de votre expédition.",
    highlights: ["Ai-je besoin d'expérience préalable ?", "Quel niveau de forme faut-il ?", "Quel est le taux de réussite au sommet ?", "Quel froid fait-il ?"],
  },
  "udzungwa-mountains-waterfalls-hike": {
    title: "Randonnée cascades dans les monts Udzungwa",
    headline: "Trek en forêt tropicale et cascades d'Udzungwa",
    location: "Parc national des monts Udzungwa",
    duration: "1 à 3 jours",
    elevation: "Jusqu'à 2 576 m",
    bestTime: "Juin - octobre",
    permits: "Frais de parc requis",
    description: "Randonnée en forêt tropicale avec cascades spectaculaires et faune endémique.",
    highlights: ["Cascades de Sanje", "Biodiversité de la forêt", "Climat agréable", "Faune endémique", "Opportunités photo"],
  },
  "usambara-mountains-cultural-walks": {
    title: "Marches culturelles dans les monts Usambara",
    headline: "Randonnées de village et culture",
    location: "Lushoto, Tanzanie",
    duration: "1 à 4 jours",
    elevation: "1 200 m - 2 300 m",
    bestTime: "Juin - octobre",
    permits: "Guide local recommandé",
    description: "Randonnée paisible sur les hauts plateaux à travers villages et points de vue panoramiques.",
    highlights: ["Marches de village", "Températures fraîches", "Rencontres culturelles", "Beaux panoramas", "Randonnée adaptée aux familles"],
  },
  "ngorongoro-highlands-empakaai-crater-trek": {
    title: "Trek du cratère d'Empakaai",
    headline: "Safari à pied sur les hautes terres du Ngorongoro",
    location: "Zone de conservation du Ngorongoro",
    duration: "1 à 2 jours",
    elevation: "3 200 m",
    bestTime: "Juin - octobre, janvier - mars",
    permits: "Frais de conservation requis",
    description: "Randonnée guidée sur le rebord du cratère dans les hautes terres du Ngorongoro avec vues sur le lac aux flamants.",
    highlights: ["Paysages volcaniques", "Vue sur le lac aux flamants", "Décors masaï", "Randonnée d'altitude", "Idéal en extension safari"],
  },
}

export const frLocalizedOverlays = {
  safaris: frSafariOverlays,
  dayTrips: frDayTripOverlays,
  zanzibar: frZanzibarOverlays,
  adventures: frAdventureOverlays,
  destinations: frDestinationOverlays,
  treks: frTrekOverlays,
}
