name: release-to-production
run-name: release-to-production
on:
  issue_comment:
    types: [created]
jobs:
  release-production:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      - name: Check aws version
        run: |
          aws --version
      - name: Configure AWS Credentials for 1) S3
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[s3-static-website-deployment]" >> ~/.aws/credentials
          echo "region=af-south-1" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      - name: Release production to S3 bucket
        run: |
          ./scripts/cd/release-production.sh
