name: release-to-production
run-name: release-to-production
on:
  issue_comment:
    types: [created]
jobs:
  release-production:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          fetch-depth: 0 # fetch all branches for Nx

      # Install AWS CLI
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: true

      # Verify AWS CLI Installation
      - name: Check aws version
        run: |
          aws --version

      # Configure AWS Credentials
      - name: Configure AWS Credentials for 1) S3
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=af-south-1" >> ~/.aws/config

      # Deploy Frontend to S3
      - name: Release production to S3 bucket
        run: |
          ./scripts/cd/release-production.sh s3

      # Deploy Backend to Lambda
      - name: Deploy backend to AWS Lambda
        run: |
          ./scripts/cd/release-production.sh lambda
